### ISSUE TITLE
iTerm not opening new tab

### ISSUE THREAD

**Issue by zamith** [tpope/vim-dispatch#111]
When I run Dispatch it runs the task and if I run `Copen` the output is there, so I'm assuming it is working well.

However, it does not open a new iTerm tab, it just sends vim to the background, runs the tasks and brings vim back, the same thing that happens when running any command on the shell.

I'm using regular vim, no gVim or MacVim, if that helps.

**Comment by tpope** [comment]
As documented, iTerm support doesn't work in the terminal for foreground invocations. The GUI subsystem is required to report back on completion of the task. `:Dispatch!` should work.

**Comment by lowski** [comment]
@tpope is this still an issue? I don't see anything about it in the README. The same happens (vim goes to background, command executes and then vim is brought back) when I use regular OS X terminal.

**Comment by tpope** [comment]
The README doesn't dive into such minutiae but it's definitely covered in [the docs](https://github.com/tpope/vim-dispatch/blob/69fea418692f76058d5cd95f0a17ed6b0f5bbb77/doc/dispatch.txt#L145-L149). Terminal.app is not supported at all.
