### ISSUE TITLE
Show successful output build

### ISSUE THREAD

**Issue by petobens** [tpope/vim-dispatch#113]
I have the following function to run a python script and, when there are errors, display them in the quickfix window:

    function! PythonDispatch()
        let l:save_pwd = getcwd()
        let old_efm = &l:efm
        lcd %:p:h
        let current_file = expand('%:p:t')
        let compiler = 'python '
        let &l:makeprg = compiler . current_file

        setlocal errorformat=
            \%A\ \ File\ \"%f\"\\\,\ line\ %l\\\,%m,
            \%C\ \ \ \ %.%#,
            \%+Z%.%#Error\:\ %.%#,
            \%A\ \ File\ \"%f\"\\\,\ line\ %l,
            \%+C\ \ %.%#,
            \%-C%p^,
            \%Z%m,
            \%-G%.%#,
            \%-G%.%#

        execute 'silent Make'

        let &l:efm = old_efm
        execute 'lcd ' . l:save_pwd
    endfunction

However when the build is succesful (i.e there are no errors) the only message I get is 
> Finished: python {python file}

and what I want is to see the output of a successful build in a preview window (or the quickfix window itself).

I tried to modify the function above by adding the following line after `execute 'silent Make'`:

        au QuickfixCmdPost cgetfile exe "silent! call " ShowPyOutput(current_file)

where 

    function! ShowPyOutput(file)
        if empty(getqflist())
            let output = split(system('python ' . a:file), "\n")
            let height = len(output)
            if empty(output)
                pclose
                echo 'No python output.'
                return
            endif
            pclose
            if height < 12
                execute "botright " . height . "new python_output"
            else
                execute "botright 12new python_output"
            endif
            setlocal buftype=nofile bufhidden=delete noswapfile nowrap previewwindow
            redraw
            call append(line('$'), output)
            normal dd
            wincmd p
        endif
    endfunction

but this doesn't work (I think there is a problem with my `QuickfixCmdPost` autocommand when it tries to expand `current_file`). Even if I make it work (by replacing `current_file` with a particular file name such as `foo.py`) the main problem is that I'm rerunning the python file using `system()` to capture the output. 

So my question is:  can I capture a successful build output by running `:Make` (or similar) only once and then display that output in a preview window?

Sorry for such a long question and thanks in advance for any kind of help!

**Comment by tpope** [comment]
Remove `%-G%.%#` from your error format and all output will be captured.

**Comment by petobens** [comment]
@tpope  thanks. If I write the errorformat like:

    setlocal errorformat=
        \%A\ \ File\ \"%f\"\\\,\ line\ %l\\\,%m,
        \%C\ \ \ \ %.%#,
        \%+Z%.%#Error\:\ %.%#,
        \%A\ \ File\ \"%f\"\\\,\ line\ %l,
        \%+C\ \ %.%#,
        \%-C%p^,
        \%Z%m,
        \%-GTraceback%.%#

Then I do capture the output but I have to manually run `:copen` once a successful build finishes. Is there a way to automatically open the quickfix window?

**Comment by tpope** [comment]
Explicitly include `%+G%.%#`.

**Comment by petobens** [comment]
Thanks again. The problem with including `%+G%.%#` is that if I have a `foo.py` file like 

    print('foo')
    x

and I run it, then in the quickfix window I get

    || foo
    foo.py|2| in <module> NameError: name 'x' is not defined
 
 and in this case I only want to obtain the error:

 foo.py|2| in <module> NameError: name 'x' is not defined

and not the `|| foo` output.

**Comment by petobens** [comment]
@tpope  One last question: how I can modifiy the errorformat to print `foo` in the quickfix instead of `||  foo` (i.e I want to  remove the `|| `.) Sorry for being such a nuisance and thanks for all the great help!

**Comment by tpope** [comment]
You can't.

**Comment by petobens** [comment]
Okay.  Thanks again for the help

**Comment by petobens** [comment]
@tpope  is it possible to trigger the `QuickFixCmdPost` autocommand just with one specific function? For instance with the following minimal vimrc the autocommand gets triggered when calling either  `RunPython()`  or `MyFlake8()`. I would like to trigger the autocommand only when calling `RunPython()`. Can I achieve that somehow? Thanks in advance for the help.

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath+=$DOTVIM/bundle/dispatch/
filetype plugin indent on

function! RunPython()
    let l:save_pwd = getcwd()
    lcd %:p:h
    let current_file = expand('%:p:t')
    let compiler = 'python '
    let &l:makeprg = compiler . current_file
    execute 'silent Make'
    execute 'lcd ' . l:save_pwd
endfunction

function! OpenBuffer()
    execute "silent botright new py_output"
    call append(line('$'), "This should only show up when running RunPython()")
    normal dd
endfunction

function! MyFlake8()
    let l:save_pwd = getcwd()
    lcd %:p:h
    let current_file = expand('%:p:t')
    let compiler = 'flake8 '
    let &l:makeprg = compiler . current_file
    execute 'silent Make'
    execute 'lcd ' . l:save_pwd
endfunction

augroup test_au
    au!
    au QuickFixCmdPost cgetfile call OpenBuffer()
augroup END
```

![tpope](https://cloud.githubusercontent.com/assets/2583971/6513142/a9fffdf2-c357-11e4-8184-c45b7cff0ce7.gif)

**Comment by tpope** [comment]
You can conditionally check `&makeprg` inside the callback function.

**Comment by petobens** [comment]
@tpope. Thank you!!!
