### ISSUE TITLE
Way to use aliases in commands?

### ISSUE THREAD

**Issue by BatmanAoD** [tpope/vim-dispatch#116]
Is there a way to use `Dispatch` with Bash aliases? I realize doesn't appear to be the intended use-model, but if there's an easy way to make it work, that would be great. (I tried searching for `alias` in the existing issues, but neither issue appeared to be dealing with shell aliases.)

I tried the following, which did not appear to work (`<file>` is an absolute path to the file where the desired alias is defined):

    let b:dispatch = '/bin/bash -c ". <file> ; shopt -s expand_aliases; <alias>"' 

I may need to set my `shellcmdflag` to something else; I have it at the default `-c`.

**Comment by justinmk** [comment]
It requires an interactive shell.

**Comment by tpope** [comment]
Yes, you can add `-i` but that has all sorts of side effects and I don't recommend it.
