### ISSUE TITLE
Open quickfix window if Make! returns errors

### ISSUE THREAD

**Issue by acurl** [tpope/vim-dispatch#117]
Hi!

Is there a way to open the quickfix window if the Make! command returns errors?

Thanks!

**Comment by tpope** [comment]
No, that's a defining difference between `:Make` and :Make!`

**Comment by acurl** [comment]
No because if I use Make, if the compiling command takes a long a time, it's a long time during when I can't continue to edit my file.
What I'd like is to have the compilation in background, and if there are errors, display the quickfix window.

**Comment by tpope** [comment]
Use a different adapter then, like tmux.

**Comment by acurl** [comment]
I don't like to have to run vim in Tmux. It takes two much steps to simply run vim and my Tmux is already configured for other things.
Furthermore, it seems that in Tmux, it will still open a new window. And in my configuration, I can't afford to loose even a few lines of my vim window.

**Comment by tpope** [comment]
What you are asking for is unsupported and literally impossible.

**Comment by acurl** [comment]
I finally managed to get what I wanted.
I inspired myself from this script https://github.com/vim-scripts/makebg
So it's possible!
