### ISSUE TITLE
Tmux pane output mangled

### ISSUE THREAD

**Issue by siphiuel** [tpope/vim-dispatch#118]
When running `:Make` in tmux 1.9a in OS X Terminal (10.10.2) I get a mangled output, similar to the one in  [Issue 59](https://github.com/tpope/vim-dispatch/issues/59):
```
|| > Building 0% > :compileJava^[[28D^[[0K2 errors
|| > Building 0% > :compileJava^[[15D^[[0K^[[13D^[[0K:compileJava
|| > Building 0%^[[13D^[[0K^[[1A^[[13CFAILED
|| > Building 0%^[[13D^[[0K^[[1A^[[19C
|| > Building 0%^[[2D33%^[[14D^[[0K
|| > Building 33%^[[14D^[[0KFAILURE:
```
After setting `let pipepane = 0` in `dispatch#tmux#make()`, I do get proper error results that are navigable through quickfix list. Still, temporary tmux pane does not have proper text colors. Is there any way I could get both proper colors and quickfix navigation?

P.S. Thanks for a great plugin!

**Comment by tpope** [comment]
The tmux adapter strips color codes but this looks like a much more elaborate progress bar. You can try to tweak the patterns passed to `sed`, but I'm guessing no, it's not feasible to get both.

**Comment by divchenko** [comment]
I got same problem with our custom build tool. Can we add an option to disable colors?
Otherwise, plugin is just awesome!

**Comment by tpope** [comment]
Add a `%\e` to `'errorformat'` and the tmux adapter will disable `pipe-pane`, on the grounds that if you care about matching escape codes you definitely don't want this monkey business. https://github.com/tpope/vim-dispatch/blob/2e42270923f165e6fee8d051030448b3b22b3c7a/autoload/dispatch/tmux.vim#L37

**Comment by divchenko** [comment]
Awesome, thanks (I should have looked through the code first)
