### ISSUE TITLE
Quickfix window closes immediately with clang linker error

### ISSUE THREAD

**Issue by jlefley** [tpope/vim-dispatch#123]
I have been using this plugin and everything has been working great.  Today I tried it with a Makefile that uses the default OS X C++ (clang) toolchain.  Compiler errors cause the Quickfix window to appear but if linker errors are present, the window closes immediately.  :Copen! brings up the window and the error messages are present.  This is with tmux and iTerm2.  Is this because there are no source files/line numbers associated with the errors?

This is the output from the make command:
```
Undefined symbols for architecture x86_64:
  "CommandBuffer::ReceivedCommandCount()", referenced from:
      CommandBufferTest::testReceivedCommandCount() in CommandBufferTest.o
  "CommandBuffer::AddByte(unsigned char)", referenced from:
      CommandBufferTest::testReceivedCommandCount() in CommandBufferTest.o
  "CommandBuffer::CommandBuffer()", referenced from:
      CommandBufferTest::testReceivedCommandCount() in CommandBufferTest.o
  "CommandBuffer::~CommandBuffer()", referenced from:
      CommandBufferTest::testReceivedCommandCount() in CommandBufferTest.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [TestSuite] Error 1
```

**Comment by vysakh0** [comment]
I've the same issue but with `elixir's` `mix test`. It works perfectly when run with `:Dispatch rspec %`  or `:Dispatch ruby %` or `:Dispatch elixir %`. 

But when I run `:Dispatch mix test %` for a specific file and if it has an error the quickfix window closes without showing error, have to open with `:Copen` 

I think my error is also related with this issue. 

```bash
 Compiled lib/reduce.ex                                                                                                                         
 Generated project app                                                                                                                          
** (CompileError) test/meta_stuff_test.exs:5: function assert/0 undefined                                                                      
   (stdlib) lists.erl:1336: :lists.foreach/2                                                                                                  
     (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6   
```

**Comment by tpope** [comment]
If the executable is `make`, the default global `'errorformat'` is used, which is good for `make` and `gcc` and not much else. Try something like `setglobal errorformat^=%+Eclang:\ error:%.%#`

There is no built-in compiler for `mix test`, so it should just always open the quickfix window. Presumably you have a plugin that provides the compiler that is failing to match the error.

**Comment by jlefley** [comment]
Is there a way to have it keep the window open if no output matches ```errorformat``` but the command invoked has a non-zero exit code?

**Comment by tpope** [comment]
Unfortunately no, Vim's `:make` doesn't support reporting an exit status.

**Comment by jlefley** [comment]
Thanks.  Adding the pattern you suggested to errorformat causes the window to remain open.

**Comment by tpope** [comment]
BTW I have discovered that `:make`'s failure to support exit status has to do with `tee` in `'shellpipe'`, and I have some ideas for workarounds. It might be supported in the future.
