### ISSUE TITLE
NeoVim :terminal support

### ISSUE THREAD

**Issue by rstacruz** [tpope/vim-dispatch#124]
would be great for colors too :)

**Comment by tpope** [comment]
Have at it. It might have some similarity with #106.

**Comment by radenling** [comment]
I've implemented a handler for vim-dispatch which uses neovims terminal and job support. So far, I've only used it together with vim-rails and vim-test and at least those two plugins work for me. If anyone is interested it's available at https://github.com/radenling/vim-dispatch-neovim

**Comment by ohpauleez** [comment]
+1 for @radenling's job dispatch additions - they work for me on OSX and Linux.

**Comment by jeroen-dhollander** [comment]
Another +1 for @radenling's dispatcher.
Maybe this could be mentioned in the Readme.md so other people have an easier time discovering this?

**Comment by teoljungberg** [comment]
Couldn’t this be closed with #250 merged?

**Comment by rx2130** [comment]
> Couldn’t this be closed with #250 merged?

It doesn't support NeoVim :terminal. Why is this issue closed?

**Comment by teoljungberg** [comment]
> > Couldn’t this be closed with #250 merged?
> 
> It doesn't support NeoVim :terminal. Why is this issue closed?

it does, but only for :Start actions. Normal :Dispatch actions are handled through the job adapter.

**Comment by tpope** [comment]
The number one difference between using jobs and using a terminal is that some commands will detect the presence of a terminal and use it as an excuse to output a more visually appealing but impossible-to-parse format. I learned my lesson from the tmux adapter; no more unfettered terminals.

**Comment by rx2130** [comment]
> > > Couldn’t this be closed with #250 merged?
> > 
> > 
> > It doesn't support NeoVim :terminal. Why is this issue closed?
> 
> it does, but only for :Start actions. Normal :Dispatch actions are handled through the job adapter.

Since :Dispatch actions aren't support NeoVim :terminal yet, I suggest we keep this issue open so it's easier for others to notice. The help doc isn't mentioning this at all.

**Comment by tpope** [comment]
I suggest we keep it closed since it would be a net negative to implement it. 😌
