### ISSUE TITLE
Make command does not properly jump to first error 

### ISSUE THREAD

**Issue by yannack** [tpope/vim-dispatch#125]
When I use "nosetests" to build, the output, when run through the proper compiler, will give something like:
```
|| ..F
|| ======================================================================
|| FAIL: test_upper (test.TestStringMethods)
|| ----------------------------------------------------------------------
|| Traceback (most recent call last):
test.py|8| in test_upper self.assertEqual('fooa'.upper(), 'FOO')
|| AssertionError: 'FOOA' != 'FOO'
|| -------------------- >> begin captured stdout << ---------------------
|| HEYY
|| 
|| --------------------- >> end captured stdout << ----------------------
|| 
|| ----------------------------------------------------------------------
|| Ran 3 tests in 2.005s
|| 
|| FAILED (failures=1)
```
As you see the first error is in test.py, line 8. 
If I build using ":make", then after the build, the quickfix line is placed on line 6 ( `test.py|8| in test_upper self.assertEqual('fooa'.upper(), 'FOO')` ) and the buffer with the actual code, containing test.py, jumps to line 8 as expected.
But if I build using ":Make", then after the build, the quickfix line is placed on line 6 as expected but the buffer with the actual code, containing test.py, does not jump at all. I need to do `:cfirst` and `:cnext` to actually get it to jump to the first error.

I think the problem is coming from the fact that the first error is not on first line of quickfix.

If you need additional files (nosetests compiler, sample test file, etc), let me know !

**Comment by tpope** [comment]
By design. Since it runs asynchronously, a jump on completion could interrupt what you are doing.

**Comment by yannack** [comment]
Understood, makes a lot of sense. I guess I can use :cf to go to the first error manually, even simpler than doing :cf + :cn 
:-)
