### ISSUE TITLE
Dispatch doensn't work correctly in neovim

### ISSUE THREAD

**Issue by voanhduy1512** [tpope/vim-dispatch#126]
I run vim and neovim in tmux, make .nvimrc alias .vimrc
In vim, if i run `Dispatch bundle`, it will open a new tmux spilt and run bundle
In neovim, if i run `Dispatch bundle`, it will run like when i run `:!bundle`

I think dispatch should run the same in vim and neovim right?

**Comment by tpope** [comment]
It should be the same, and it is the same for me.  [This code](https://github.com/tpope/vim-dispatch/blob/e7ed067185a32ab776095b71442b55c044de5361/autoload/dispatch/tmux.vim#L13-18) encapsulates all the conditions where the tmux adapter will refuse to run, if that helps you narrow it down.

**Comment by voanhduy1512** [comment]
I try to debug and it seem the problem in [this line](https://github.com/tpope/vim-dispatch/blob/e7ed067185a32ab776095b71442b55c044de5361/autoload/dispatch/tmux.vim#L16)
This condition is true so is return

**Comment by tpope** [comment]
So what is the value of `session` and `system('tmux has-session -t '.shellescape(session))[0:-2]`?

**Comment by voanhduy1512** [comment]
I try to `echom session` and `echom system('tmux has-session -t '.shellescape(session))[0:-2]`, then `:messages` but nothing there.

```
  if empty($TMUX) && empty(''.session) || !executable('tmux')
    return 0
  endif
  echom 'debug session'
  echom session
  echom 'debug system tmux has-session'
  echom system('tmux has-session -t '.shellescape(session))[0:-2]
  if !empty(system('tmux has-session -t '.shellescape(session))[0:-2])
    return ''
  endif
```

Output:
```
debug session
debug system tmux has-session
^[Ptmux;^[^[]4;0;rgb:2b/30/3b^G^[\^[Ptmux;^[^[]4;1;rgb:bf/61/6a^G^[\^[Ptmux;^[^[]4;2;rgb:a3/be/8c^G^[\^[Ptmux;^[^[]4;3;rgb:eb/cb/8b^G^[\^[Ptmux;^[^[]4;4;rgb:8f/a1/b3^G^[\^[Ptmux;^[^[]4;5;rgb:b4/8e/ad^G^[\
^[Ptmux;^[^[]4;6;rgb:96/b5/b4^G^[\^[Ptmux;^[^[]4;7;rgb:c0/c5/ce^G^[\^[Ptmux;^[^[]4;8;rgb:65/73/7e^G^[\^[Ptmux;^[^[]4;9;rgb:bf/61/6a^G^[\^[Ptmux;^[^[]4;10;rgb:a3/be/8c^G^[\^[Ptmux;^[^[]4;11;rgb:eb/cb/8b^G^
[\^[Ptmux;^[^[]4;12;rgb:8f/a1/b3^G^[\^[Ptmux;^[^[]4;13;rgb:b4/8e/ad^G^[\^[Ptmux;^[^[]4;14;rgb:96/b5/b4^G^[\^[Ptmux;^[^[]4;15;rgb:ef/f1/f5^G^[\^[Ptmux;^[^[]4;16;rgb:d0/87/70^G^[\^[Ptmux;^[^[]4;17;rgb:ab/79
/67^G^[\^[Ptmux;^[^[]4;18;rgb:34/3d/46^G^[\^[Ptmux;^[^[]4;19;rgb:4f/5b/66^G^[\^[Ptmux;^[^[]4;20;rgb:a7/ad/ba^G^[\^[Ptmux;^[^[]4;21;rgb:df/e1/e8^G^[\^[Ptmux;^[^[]Pgc0c5ce^G^[\^[Ptmux;^[^[]Ph2b303b^G^[\^[Pt
mux;^[^[]Pic0c5ce^G^[\^[Ptmux;^[^[]Pj4f5b66^G^[\^[Ptmux;^[^[]Pkc0c5ce^G^[\^[Ptmux;^[^[]Plc0c5ce^G^[\^[Ptmux;^[^[]Pm2b303b^G^[
Press ENTER or type command to continue
```

**Comment by tpope** [comment]
I don't know what all that `^[Ptmux` garbage is but that's definitely your problem.

**Comment by voanhduy1512** [comment]
Follow thoughtbot/vim-rspec#91it's seem like there is a problem with https://github.com/chriskempson/base16-shell. Thank you very much
