### ISSUE TITLE
X11 handler is ignored in gvim

### ISSUE THREAD

**Issue by zorab47** [tpope/vim-dispatch#127]
The X11 handler is consistently skipped when running in gvim and uses the fallback headless handler.

The check for `a:request.action` in [x11.vim:9](https://github.com/tpope/vim-dispatch/blob/2f5d15fea4c9427ba3f7d8d82c838890b8522125/autoload/dispatch/x11.vim#L9) consistently returns early when invoking dispatch. My guess is because the request's action is set to "make" it causes the handler to be skipped. Should the "make" action be handled differently in the X11 handler?

Commenting out the check for `a:request.action !=# 'start'` allows the x11 handler to be used and starts a new terminal session as expected.

**Comment by tpope** [comment]
Oh, yeah, that can probably be tweaked to allow make through if `wmctrl` is available. Without `wmctrl` there is no way to return focus to Vim, which is the origin of that short circuit.

**Comment by tpope** [comment]
Try the `x11-make` branch. Make sure all 4 cases (Make/Make!/Start/Start!) work as expected and I'll merge.

**Comment by tpope** [comment]
Not sure what I was thinking. Someone needs to implement make support for this to work.

**Comment by zorab47** [comment]
The commands Make/Make!/Start/Start! all executed in the new terminal session on the `x11-make` branch. I did notice that the call to Make didn't focus the new terminal in front of gvim like Start did. Both Make!/Start! executed in the background without showing the new terminal session.

What would be involved with implementing make support?

**Comment by tpope** [comment]
Basically you need to use `prepare_make` rather than `prepare_start`. The screen adapter is probably the best source of inspiration.

**Comment by zorab47** [comment]
Thanks. I'll give it a shot.

**Comment by aripollak** [comment]
Looks like this can be closed now. The X11 support still seems pretty buggy to me, but I'll open followup bugs as I isolate them.

**Comment by tpope** [comment]
Yeah I used it for the first time yesterday and fixed a bad bug. Let me know if you find any more.
