### ISSUE TITLE
Thoughts on replacing `expand`?

### ISSUE THREAD

**Issue by teoljungberg** [tpope/vim-dispatch#129]
We're using `expand` to get the filename if `%` is passed to `:Dispatch`, if we call `:Dispatch something %:8` to run the test on line 8. Only `:Dispatch something %` will be ran, since `:8` is apart of `expand`'s flags.

Is there anyway to work around this, replacing expand with something else?

**Comment by tpope** [comment]
There are lots of ways to work around this. The easiest is probably `:Dispatch "%":8`, which adds a bit of robustness to boot. Avoid the single quote variant unless you're really really sure you don't care about Windows.

**Comment by teoljungberg** [comment]
Great, thank you!
