### ISSUE TITLE
Terminal.app support

### ISSUE THREAD

**Issue by teoljungberg** [tpope/vim-dispatch#130]
I would love to see Terminal.app support for vim-dispatch, is there a reason why this isn't the case? Was there a technical-problem? Could we use the same AppleScript as found in https://github.com/tpope/vim-dispatch/blob/master/autoload/dispatch/iterm.vim ?

**Comment by tpope** [comment]
Believe me I tried. The closest I could get was spawning a terminal and literally pasting a command into it, which I decided was an unacceptably leaky abstraction. But feel free to investigate a more elegant solution.
