### ISSUE TITLE
Running ruby minitest causes "Press ENTER' message

### ISSUE THREAD

**Issue by aripollak** [tpope/vim-dispatch#132]
Using the X11 adapter under gvim 7.4, if I run `:Dispatch ruby -Itest test/unit/blah_test.rb` (like what automatically happens in vim-rails when editing a minitest file), I get the "Press ENTER or type command to continue" message. But if I run `:Dispatch rspec spec/models/blah_spec.rb`, I don't get that message/prompt.

**Comment by tpope** [comment]
Is this just a simple matter of the message wrapping onto a second line? I don't think that's X11 specific.

**Comment by aripollak** [comment]
Oh, that's possible. I haven't tried with other adapters. Is this a bug in vim-dispatch or some other vim thing, or is there a workaround? This also seems to be related to my other issue, which is that the quickfix window doesn't auto-open for minitest, which seems to be because `:cw` doesn't seem to detect any errors.

**Comment by tpope** [comment]
Vim loves "press enter" prompts; I don't really think you can single out dispatch.vim for this. Personally I gave up and `:set cmdheight=2` years ago, largely solving the problem for me. If you have a concrete recommendation for an improvement (perhaps something to do with respecting `'shortmess'`), let me know. But otherwise I don't think there is anything to be done here.

**Comment by tpope** [comment]
Regarding minitest, I am just now pushing an experimental change to always open the quickfix on a failed exit status. But that might not help if minitest-reporters has sufficiently butchered error locations as to be completely unparsable.

**Comment by aripollak** [comment]
> But that might not help if minitest-reporters has sufficiently butchered error locations as to be completely unparsable.

Yeah, they're pretty butchered, so I think I just have to disable it when running vim, which is unfortunately not built into the gem.

**Comment by aripollak** [comment]
Thanks! You were right of course, it wasn't testunit vs. rspec, it was the length of the commandline. With that new fix, at least I'll be able to see the errors instead of the "failure" message disappearing quickly.

**Comment by lencioni** [comment]
> If you have a concrete recommendation for an improvement (perhaps something to do with respecting `'shortmess'`), let me know.

I have been working on a Vim plugin where I ran into a similar issue. For our use case, we decided that truncating the messages was the best approach. This is the commit we applied this technique in our plugin: https://github.com/trotzig/import-js/commit/e29dfff8

Most of the magic is in this function:

```vim
" WideMsg() prints [long] message up to (&columns-1) length
" guaranteed without "Press Enter" prompt.
" http://vim.wikia.com/wiki/How_to_print_full_screen_width_messages
function! importjs#WideMsg(msg)
  let x=&ruler | let y=&showcmd
  set noruler noshowcmd
  redraw
  echo a:msg
  let &ruler=x | let &showcmd=y
endfun
```

What do you think about using this technique in vim-dispatch?
