### ISSUE TITLE
I'm doing something wrong...

### ISSUE THREAD

**Issue by pmcmorris** [tpope/vim-dispatch#133]
Hello, I'm new to vim and Dispatch so the problem is likely on my end. But I didn't know where else to go for help.

We have a custom/proprietary build system (i.e. not make etc.) so I figured I would get started by using dispatch to execute a simple script (it's in Lua but self explanatory):

```lua
    print("Build Failed")
    os.exit(-1)
```

But when I run  :Dispatch run_test, I can tell that it runs the command but it never shows me the output (success/fail). I can tell the script is running because when I add a line that reads from the console, the spawned window stays open. In fact, the quickfix window doesn't open at all unless Dispatch can't find my script file at all.

So how do I get it to respect the return codes and how do I get the console output back into a vim buffer?  What am I missing?

If someone could point me in the right direction, it would be much appreciated.

Patrick

**Comment by tpope** [comment]
Do you see the output if you `:Copen`?

**Comment by pmcmorris** [comment]
That does open the quickfix window but its empty.

**Comment by tpope** [comment]
What adapter is in use?

**Comment by pmcmorris** [comment]
Please hold while I go educate myself on adapters...  but I'm guessing make?

I tried :Dispatch run_test as well as :set makeprg=run_test and then just :Dispatch

**Comment by tpope** [comment]
No I mean the definition of adapter I use all over the README.

**Comment by pmcmorris** [comment]
This machine is Win7 so I'm guessing "Windows".

The status bar briefly shows:
:!run_test (windows/?)

**Comment by tpope** [comment]
Then yeah, sounds like something is broken? What is the output of `:set shellslash? shell?`?

**Comment by pmcmorris** [comment]
noshellslash
  shell=C:\windows\system32\cmd.exe

**Comment by tpope** [comment]
Doubtful it will help in the case but can you try with other plugins disabled and a stripped down config?

What exact version of Vim/patch level?

**Comment by pmcmorris** [comment]
I reduced my .vimrc to this:

```vim
" explicitly get out of vi-compatible mode
set nocompatible

" initial vundle package manager
	filetype off " disable filetype detection temporarily
	set rtp+=~/.vim/bundle/Vundle.vim/
	call vundle#begin()

	" Use :VundleInstall before adding here
	Bundle 'gmarik/Vundle.vim'
	Bundle 'tpope/vim-dispatch'

	call vundle#end()
	filetype plugin indent on " enable filetype detection and per type scripts and indenting
```

Same results though.  Its a stock version of gvim 7.4.  I'm not sure how to get the patch level but this is my version info (and I'll go look for a newer version)

:version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 10 2013 14:33:40)
MS-Windows 32-bit console version
Compiled by mool@tororo
Big version without GUI.  Features included (+) or not (-):
+arabic          +conceal         +extra_search    +langmap         +multi_lang      +rightleft       -tcl             +wildignore
+autocmd         +cryptv          +farsi           +libcall         -mzscheme        -ruby            -tgetent         +wildmenu
-balloon_eval    +cscope          +file_in_path    +linebreak       -netbeans_intg   +scrollbind      -termresponse    +windows
-browse          +cursorbind      +find_in_path    +lispindent      +path_extra      +signs           +textobjects     +writebackup
++builtin_terms  +cursorshape     +float           +listcmds        -perl            +smartindent     +title           -xfontset
+byte_offset     +dialog_con      +folding         +localmap        +persistent_undo -sniff           -toolbar         -xim
+cindent         +diff            -footer          -lua             -postscript      +startuptime     +user_commands   -xterm_save
+clientserver    +digraphs        +gettext/dyn     +menu            +printer         +statusline      +vertsplit       -xpm_w32
+clipboard       -dnd             -hangul_input    +mksession       -profile         -sun_workshop    +virtualedit
+cmdline_compl   -ebcdic          +iconv/dyn       +modify_fname    -python          +syntax          +visual
+cmdline_hist    +emacs_tags      +insert_expand   +mouse           -python3         +tag_binary      +visualextra
+cmdline_info    +eval            +jumplist        -mouseshape      +quickfix        +tag_old_static  +viminfo
+comments        +ex_extra        +keymap          +multi_byte      +reltime         -tag_any_white   +vreplace
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32   -DFEAT_CSCOPE       -DWINVER=0x0400 -D_WIN32_WINNT=0x0400  /Fo.\ObjCi386/ /Ox /GL -DNDEBUG  /Zl /MT -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_BIG /Fd.\ObjCi386/ /Zi
Linking: link /RELEASE /nologo /subsystem:console /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib uuid.lib /machine:i386 /nodefaultlib  libcmt.lib   user32.lib             /PDB:vim.pdb -debug

**Comment by tpope** [comment]
I guess my next step would be to recommend trying older versions and see if you can find one that works? Either that or you're going to have to get your hands dirty with VimL.

**Comment by pmcmorris** [comment]
The problem doesn't seem to appear if I use a batch file which launches the script rather than launching the script directly.  I'll dig deeper once I get some spare time.  If I learn anything new I'll post it here.

**Comment by tpope** [comment]
Oh, yeah, wouldn't be surprised if that has something to do with `PATH` or `PATHEXT` not being set correctly inside vim.
