### ISSUE TITLE
Fire user autocommands after dispatch is complete

### ISSUE THREAD

**Issue by wincent** [tpope/vim-dispatch#135]
I've got another plug-in which I'd like to use to extend vim-dispatch's functionality. What do you think of having vim-dispatch fire an autocommand after each dispatch is complete, so that the other plug-in can hook in and do some extra stuff? (Specifically, I'm running searches and I want to do some post-processing over the results).

If you're open to the autocommands, let me know and I'll put together a pull request.

**Comment by tpope** [comment]
It already fires a `cgetfile` when the results are loaded, which sounds like the event you want.

**Comment by wincent** [comment]
Excellent, thanks @tpope.
