### ISSUE TITLE
When quick fix window open?

### ISSUE THREAD

**Issue by voanhduy1512** [tpope/vim-dispatch#136]
Hi tpope,
This is more like a question then an issue.
When run `:Dispatch bundle` in vim (with tmux), when it ran successfully, the spilt close.
When run `:Dispatch ls`, after success the split close but `Quickfix window` open.
Both return error code 0 but behave different.
Could you tell me what is the different and how I change it to show Quickfix only when command return error

Thanks.

**Comment by tpope** [comment]
It's based on if the compiler plugin finds any errors. For commands like `ls` with no compiler plugin it always opens.
