### ISSUE TITLE
Vim loses focus when using Start!

### ISSUE THREAD

**Issue by petobens** [tpope/vim-dispatch#142]
With the following minimal vimrc:

```vim
set nocompatible
let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')
set runtimepath+=$DOTVIM/bundle/dispatch
filetype plugin indent on
```

If I run `Start! notepad.exe` then  Gvim loses focus when notepad opens(this can be seen in the GIF below). How can I start notepad (actually any program) in a new unfocused window (if possible minimized)? Thanks in advance for any kind of help. 

![blah](https://cloud.githubusercontent.com/assets/2583971/9179171/1b3a735e-3f71-11e5-8da0-d21bc45d4874.gif)

**Comment by tpope** [comment]
`:Start!` will background the `cmd.exe` window, but if that window in turn spawns another GUI app, I don't think anything can be done on the dispatch.vim side. You can maybe pass an argument to notepad itself or whatever to ask it to minimize.

**Comment by petobens** [comment]
Thanks @tpope for the quick reply.
