### ISSUE TITLE
difference, hard for me to understand need your help.

### ISSUE THREAD

**Issue by shimoby** [tpope/vim-dispatch#144]
i just trying to figure out what is the difference between this two

from vim command                                     type            :Dispatch npm test

and

open new pane in tmux and type from command line     npm test --watch(listens file change)

could you please help me to understand i am read lots of text prior to ask this trivial matter to you . obviously i am overlooking something everyone keep telling that is how awesome but i still trying to grasp the real advantage.

thank you for you work and support vim world.

**Comment by symbolix** [comment]
It is probably the fact that `:Dispatch npm test` will capture the output of the process and feed it into the `Quickfix List`. I am new to `vim-dispatch` myself and I have never used `npm`. But I find it helpful that I can fire up a command from my vim session and observe the results in the `Quickfix List`. In parallel to this, I also do the plain "just send a command to tmux" approach and have stuff running in a tmux pane.

**Comment by tpope** [comment]
Yes and with a compiler plugin it can parse out filenames etc
