### ISSUE TITLE
:Make arguments accumulate

### ISSUE THREAD

**Issue by hammacher** [tpope/vim-dispatch#145]
I often have to run `:Make` with additional arguments, like `:Make -s -j4 -C /usr/build/foo test`.
These arguments seem to accumulate over time, so that after a while, I see vim output like this:

> :!make -s -j4 -C /usr/build/foo test -s -j4 -C /usr/build/foo test -s -j4 -C /usr/build/foo test -s -j4 -C /usr/build/foo test -s -j4 -C /usr/build/foo test -s -j4 -C /usr/build/foo test -s -j4 -C /usr/build/foo test -s -j4 -C /usr/build/foo test (tmux/19007)
> Press ENTER or type command to continue

It seems that sometimes, `:Make` remembers arguments from previous invocations. Then, it is also sufficient to just type `:Make`, and it still uses the old arguments. But this seems to not always be the case. Can someone clarify?

**Comment by hammacher** [comment]
Hm, thanks for the answer. Grepping for `QuickFixCmdPre` and `QuickFixCmdPost` in my `~/.vim` folder only shows these unsuspicious hits:
> .vim/bundle/ctrlp/autoload/ctrlp/mrufiles.vim:          au QuickFixCmdPre  *vimgrep* let s:locked = 1
> .vim/bundle/tagbar/autoload/tagbar.vim:        autocmd QuickFixCmdPre  * let s:tagbar_qf_active = 1
> .vim/bundle/vim-dispatch/autoload/dispatch.vim:    silent doautocmd QuickFixCmdPre dispatch-make-complete
> .vim/bundle/vim-dispatch/autoload/dispatch.vim:    silent doautocmd QuickFixCmdPre dispatch-make
> .vim/bundle/vim-dispatch/autoload/dispatch.vim:    silent doautocmd QuickFixCmdPre cgetfile
> .vim/bundle/ctrlp/autoload/ctrlp/mrufiles.vim:          au QuickFixCmdPost *vimgrep* let s:locked = 0
> .vim/bundle/tagbar/autoload/tagbar.vim:        autocmd QuickFixCmdPost * if exists('s:tagbar_qf_active') |
> .vim/bundle/vim-dispatch/autoload/dispatch.vim:    silent doautocmd QuickFixCmdPost dispatch-make-complete
> .vim/bundle/vim-dispatch/autoload/dispatch.vim:    silent doautocmd QuickFixCmdPost dispatch-make
> .vim/bundle/vim-dispatch/autoload/dispatch.vim:    silent doautocmd QuickFixCmdPost cgetfile

Any idea how to track this down further?

**Comment by tpope** [comment]
I would make sure you can reproduce the issue with a bare install of dispatch.vim only, as there are other ways plugins can interfere. For example, a plugin that does a window refocus at the wrong time could cause a save/restore of `'makeprg'` to happen in the wrong window.

**Comment by tpope** [comment]
FYI https://github.com/tpope/vim-dispatch/blob/69fea418692f76058d5cd95f0a17ed6b0f5bbb77/autoload/dispatch.vim#L835 is the line that temporarily changes `'makeprg'` to include the full arguments, in case an enterprising autocommand wants to consult them. The `finally` cause should restore it, save for the aforementioned case where an autocommand changes the window or buffer.

**Comment by hammacher** [comment]
Oh damn, it was in my own `.vimrc` :( 
Years ago, before I started using `vim-dispatch`, I added these lines to the `.vimrc` (according to http://vim.wikia.com/wiki/Automatically_open_the_quickfix_window_on_:make):
> autocmd QuickFixCmdPost [^l]* nested cwindow
> autocmd QuickFixCmdPost    l* nested lwindow

Your plugin makes them superfluous, and removing them eliminates my problem.
Thanks a lot for your help!
