### ISSUE TITLE
Support for -a option for tmux new-window command

### ISSUE THREAD

**Issue by DXist** [tpope/vim-dispatch#147]
Basically, I want to create new tmux window next to the window with Vim, not at the end of window list.

It works if `new-window` is called with `-a` option.

**Comment by tpope** [comment]
This seems like a benign thing to make configurable, but let's think through all the variations of this so we don't end up with option sprawl. For starters, which of `:Start`, `:Start!`, and `:Dispatch!` do you care about? Are there other options that would make sense to pass to `new-window`? What about `split-window`?

**Comment by DXist** [comment]
Personally I use `:Start` to fire up interactive debugging sessions.

Actually, tmux is smart enough to remember last window position. I just moved interactive window next to the window with Vim. After that `:Start` window is opened in the same location. This behaviour is totally fine by me.

I realised this after I've created this issue and it seems no more actual for me. Sorry for inconvenience and thank you so much for really useful plugin!
