### ISSUE TITLE
After viewing and closing quickfix, should it pop up when next Dispatch! is called?

### ISSUE THREAD

**Issue by mwcz** [tpope/vim-dispatch#148]
I'm seeing this behavior and not sure if it's intentional or not.

 1. open file, run `:Dispatch!`
 2. curious about output, I run `:Copen`
 3. close quickfix window with either `:bd` or `:cclose`

Now, the next time I run `:Dispatch!` the quickfix window will immediately open, shownig the output from the previous dispatch.  Is there a way to have the quickfix window only open when `:Copen` is run?

Sorry if I'm missing something obvious!

**Comment by tpope** [comment]
Definitely shouldn't happen. Sure it's not a weird autocommand in your vimrc?

**Comment by mwcz** [comment]
Nothing that jumps out at me.  Here are all my autocmds.

    autocmd BufEnter * :syntax sync fromstart
    autocmd FileType css,scss,less set iskeyword=@,48-57,_,-,?,!,192-255
    autocmd FileType javascript let b:dispatch = 'grunt build:dev && beep'

I do have some [more
autocmds](https://github.com/mwcz/vim-mwcz-config/blob/master/vimrc#L627) but they only affect cmdwin.

**Comment by tpope** [comment]
See if you can reproduce with a minimal, Dispatch only setup. The only cause I can imagine for this is a rogue `QuickFixCmdPre` or `QuickFixCmdPost` autocommand somewhere.

**Comment by mwcz** [comment]
Yeeeeeeep, you're the man.  The conflict was caused by [wincent/ferret](https://github.com/wincent/ferret) which I don't remember installing but apparently did at some point.  Removed it and all is well, thank you sir!
