### ISSUE TITLE
quickfix not matching any errorformat

### ISSUE THREAD

**Issue by mellery451** [tpope/vim-dispatch#151]
A plea for help - most likely I'm just not aware how to do this the right way.

I have the following:

    nmap <leader>W :Dispatch ~/bin/make_wrapper win<CR>

..which calls some custom shell stuff to invoke a remote windows build and gather the output.

That works great, but the quickfix that opens just refuses to parse the output. I've tried adding all kinds of things to my errorformat setting, but no luck.

FWIW, a typical error coming from this system looks like:

|| /a/full/path/to/some/source/file.cc(24): error C2059: syntax error : ';' [/a/full/path/to/the/project/file.vcxproj] -- [THREAD 17]

..for which I've added:

    set errorformat+=\ %#%f(%l)\ :\ %#%t%[A-z]%#\ %[A-Z\ ]%#%n:\ %m

Is it possible that I've missed something and quickfix is simply not even using my (extensive) errorformat string? Do I need to do some trickery to make it *think* there is a compiler involved here?

My custom make script is already doing lots of stdout/stderr munging, so it makes more sense just to translate the output to a format that quickfix will just recognize, I'm fine with that instead..just not sure what format to translate to.

This is all admittedly due to my woeful ignorance of how make/quickfix works in vim in general.

Thanks.

**Comment by tpope** [comment]
`:Dispatch` by design ignores the global error format. You can use `:Make` instead with the right `'makeprg'` or create a compiler plugin.
