### ISSUE TITLE
Run another vim command with vim-dispatch

### ISSUE THREAD

**Issue by awakenrz** [tpope/vim-dispatch#152]
I have a long running vim command, say :foo, that I would like to run with dispatch. Is it possible?

I tried :Dispatch :foo and the command still runs in foreground without opening a new tab in tmux.

Any ideas?

**Comment by tpope** [comment]
Negative. Vim lacks async capabilities, full stop.

**Comment by justinmk** [comment]
@awakenrz You can do it in Neovim with `jobstart()`.

**Comment by tpope** [comment]
Since when can Neovim run arbitrary Vim commands asynchronously?

**Comment by justinmk** [comment]
Sorry, didn't catch that detail--it will be possible pretty soon though.
