### ISSUE TITLE
XMonad and i3 support

### ISSUE THREAD

**Issue by cyberguijarro** [tpope/vim-dispatch#155]
Hey, great plugin. It would be even better with extended plugin support for i3, XMonad and other tiling window managers.

**Comment by tpope** [comment]
Meaning?

**Comment by cyberguijarro** [comment]
Same way you open new sessions under tmux or iTerm, the plugin could also open new splits/tabs in XMonad, i3 or gnome-terminal.

**Comment by tpope** [comment]
Okay, how specifically would you go about implementing that? A tmux style split for `:Dispatch` sounds interesting but I suspect both WM's would fight you on it.

**Comment by cyberguijarro** [comment]
Actually, maybe I've expressed this the wrong way: you could just open any X-based terminal emulator (xterm, gnome-terminal, etc) just like you open cmd.exe in Windows. The window manager will handle the rest putting the new window on its own split, then removing the split when the window is closed.

**Comment by tpope** [comment]
The X11 adapter already does that.

**Comment by cyberguijarro** [comment]
Well, for whatever reason the x11 adapter won't work on my system and vim-dispatch defaults to "headless" :/

I'll investigate and see what the problem might be.

**Comment by tpope** [comment]
You can enable `XMonad.Hooks.EwmhDesktops` to fix that. (The fact it is off by default is typical of it's academic approach to a real world problem.)
