### ISSUE TITLE
Dispatch creates window instead of pane with Tmux 2.1

### ISSUE THREAD

**Issue by jimmyharris** [tpope/vim-dispatch#156]
Attempting to run Make or any other dispatch command with tmux causes tmux to create a new window instead of creating a new pane in the current window. Any way we can fix this?  I am not sure what changed between tmux 2.0 and tmux 2.1 to cause this to happen.

**Comment by tpope** [comment]
My guess is something in [this conditional](https://github.com/tpope/vim-dispatch/blob/69fea418692f76058d5cd95f0a17ed6b0f5bbb77/autoload/dispatch/tmux.vim#L46) changed,. That is, either `$TMUX` is no longer set or `tmux display-message -p "#S"` no longer works. Please confirm.

**Comment by jimmyharris** [comment]
It appears that both the environment variable and the command you mentioned work as expected.

**Comment by jimmyharris** [comment]
I figured out the issue.

When I run NeoVim with the environment variable NVIM_TUI_ENABLE_TRUE_COLOR=1 set. NeoVim reports `has('gui_running')` as true in order to make colorschemes use their GUI directives instead of their console directives. This might also be triggering some other issues I am seeing with NeoVim's True Color mode.

**Comment by tpope** [comment]
Okay, filing this under "not my problem". It is permissible to specify gui attributes when the gui isn't running, so really this is just accommodating broken color schemes.

**Comment by jimmyharris** [comment]
Yea. I am giving up on true color mode for a lot of reasons right now.

**Comment by mellery451** [comment]
FWIW looks like this might be in the process of being [fixed in nvim](https://github.com/neovim/neovim/pull/4155)

**Comment by jimmyharris** [comment]
I saw that. This is a much better decision on NeoVim's part.  Thanks for being so responsive on your open source projects.
