### ISSUE TITLE
Feature to open quickfix list only on failure

### ISSUE THREAD

**Issue by orlp** [tpope/vim-dispatch#161]
I am aware this [has been requested before](https://github.com/tpope/vim-dispatch/issues/23), but the situation has changed. Inspecting the `dispatch#complete` function you are now capable of extracting the error code of the program ran.

My suggestion is to add a command - for example `:DispatchSilentSuccess` that works exactly like `:Dispatch`, except that it does not open the quickfix list if the command returned without error.

I often want to run some command that produces output on success, but do not want to (or it's impossible to) write an `errorformat` just for that command.

**Comment by orlp** [comment]
A suggested implementation would be to change the following line in `dispatch#complete`:

        if !request.background

To something like this:

        if !request.background && !(request.silent_success && status == 0)

And propagate `request.silent_success` in some way from `:DispatchSilentSuccess`.

**Comment by tpope** [comment]
The fact we now always open on failure means you can make **one** additional compiler that never matches anything (`:CompilerSet errorformat=this\ line\ never\ matches`), and then call it with `:Dispatch -compiler=ignore ...` (or whatever you named it). Anything that doesn't solve? We could certainly add another option (like `:Start -wait=never`) but I'm not seeing a need.

**Comment by orlp** [comment]
@tpope If I understand you correctly that doesn't work, because it *never* opens the quickfix menu.

What I want is a quickfix menu that opens iff:

1. The command generated output.
2. The command had a non-zero return code.

When both above conditions are met, I __do__ want to see a quickfix menu.

**Comment by tpope** [comment]
You misunderstand the first 8 words.

**Comment by orlp** [comment]
@tpope Ah, I see. Well then that should do, I believe.

**Comment by senbrow** [comment]
[vim-noerror-compiler](https://github.com/senbrow/vim-noerror-compiler) is a tiny plugin you can install with vundle to accomplish what tpope mentioned like so:
`:Dispatch -compiler=noerror commandWithOutputIDontCareAbout`
