### ISSUE TITLE
nvim: Unknown option argument: "--servername" 

### ISSUE THREAD

**Issue by mellery451** [tpope/vim-dispatch#163]
I've just switched to neovim, this version:

```
NVIM 0.1.1 (compiled Jan 26 2016 13:10:50)
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20160126-62152-16i86gd/neovim-0.1.1/build/config -I/tmp/neovim20160126-62152-16i86gd/neovim-0.1.1/src -I/tmp/neovim20160126-62152-16i86gd/neovim-0.1.1/deps-build/usr/include -I/tmp/neovim20160126-62152-16i86gd/neovim-0.1.1/deps-build/usr/include -I/tmp/neovim20160126-62152-16i86gd/neovim-0.1.1/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20160126-62152-16i86gd/neovim-0.1.1/deps-build/usr/include -I/tmp/neovim20160126-62152-16i86gd/neovim-0.1.1/deps-build/usr/include -I/tmp/neovim20160126-62152-16i86gd/neovim-0.1.1/deps-build/usr/include -I/tmp/neovim20160126-62152-16i86gd/neovim-0.1.1/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -I/tmp/neovim20160126-62152-16i86gd/neovim-0.1.1/build/src/nvim/auto -I/tmp/neovim20160126-62152-16i86gd/neovim-0.1.1/build/include
Compiled by mellery@mellery-mbpr

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.1/share/nvim"
```
I have a number of custom shell commands mapped to dispatch. With nvim, I seem to be getting an error about --servername:

```
|| CURRENT DIR is  ~~[REDACTED]~~
|| CURRENT DIR BASENAME is ~~[REDACTED]~~
|| executing [clean] in ~~[REDACTED]~~
|| nvim: Unknown option argument: "--servername"
|| More info with "nvim -h"
```
The first three lines of output are mine - last two are unexpected.  Is there something that I need to change in the way I invoke Dispatch, perhaps?  My maps typically look like:

`nmap <leader>T :Dispatch my_command arg_1 arg_2<CR>`

Thanks!

**Comment by tpope** [comment]
What does `:echo v:servername` report?

**Comment by mellery451** [comment]
screenshot - because I'm too lazy to figure out how to echo into a buffer...

<img width="584" alt="screen shot 2016-01-26 at 2 50 14 pm" src="https://cloud.githubusercontent.com/assets/463430/12597956/6a75664a-c43c-11e5-9e54-02237881a9fb.png">

**Comment by justinmk** [comment]
Neovim doesn't implement `+clientserver` feature of Vim, and we haven't restored `--servername` argument yet.

`echo v:servername` is reporting the domain socket name of the current server, but it's not going to be of much use to dispatch.

Hoping someone will get around to implementing a Neovim strategy for dispatch that uses `jobstart()` and friends--would be a great use-case, in particular it allows feedback from background jobs without the SIGWINCH hack.

**Comment by tpope** [comment]
In the mean time can you offer an ideally future-proof recommendation for how I should alter the conditional? My first thought was "servername doesn't start with a slash" but technically that's allowed.

**Comment by mellery451** [comment]
@justinmk  -- seems like there might be something close in https://github.com/radenling/vim-dispatch-neovim   ?

**Comment by justinmk** [comment]
@tpope `dispatch#callback` could remain as-is, because `--remote-expr` will work the same way when it's restored. Of course `dispatch#vim_executable` would need to be modified to return `nvim`.

In other words: when `--remote-expr` and `--servername` are restored, they'll always work with Neovim. The future-proof way to avoid them would be to prefer `jobstart()` instead. Other than that, only way I can think of is to add a `has("nvim-1.2.3")` feature to Neovim that works like Vim's `has("patch-1.2.3")`. I'll update here when that's implemented.

**Comment by tpope** [comment]
Wait, why can't I just check `has('clientserver')`?

**Comment by justinmk** [comment]
@tpope You can; I was thinking we might not want to return truthy for that even if we restore `--remote-expr` and `--servname` because the behavior won't necessarily match Vim. I haven't looked at it closely enough to guarantee a "future proof" strategy there. But it's probably fine.

**Comment by tpope** [comment]
FYI a first class neovim handler would be great, but at 175 lines I am highly suspicious of the one mentioned above. Every existing adapter is a hack in some way and yet all are substantially smaller than what should in theory be the cleanest of them all?

**Comment by mellery451** [comment]
the fix works for me - thanks!
