### ISSUE TITLE
Neovim + Tmux isn't splitting on foreground call

### ISSUE THREAD

**Issue by rgrinberg** [tpope/vim-dispatch#164]
Doing a `Make` in vim will correctly create a split below the current window. While in neovim, this will create a whole new window. It would be great if this worked the same for neovim.

**Comment by tpope** [comment]
There is not yet official Neovim support so this is presumably coming from a 3rd party Dispatch adapter.

**Comment by rgrinberg** [comment]
I don't think I have any 3rd party dispatch adapters installed. Is there a way to check what it is currently?

**Comment by tpope** [comment]
For starters are you talking about tmux splits?

**Comment by rgrinberg** [comment]
Exactly, I guess I should say "pane"

**Comment by tpope** [comment]
Here's the only conditional afaik that could conceivably allow for the behavior you describe: https://github.com/tpope/vim-dispatch/blob/e8c075f30d6e003e94c6bab6e37d4e5f7f6056cc/autoload/dispatch/tmux.vim#L44-L50

**Comment by rgrinberg** [comment]
`has('gui_running')` is `1` for me even though i'm running neovim under iterm + tmux.

**Comment by rgrinberg** [comment]
OK it's because I have true color enabled:

```
let $NVIM_TUI_ENABLE_TRUE_COLOR=1
```

**Comment by rgrinberg** [comment]
Would it be possible to override the `has('gui_running')` somehow?

Neovim specific hack perhaps?

**Comment by tpope** [comment]
If Neovim is going to outright lie like that than surely they at least provide a straightforward workaround?

**Comment by rgrinberg** [comment]
@justinmk says he has something cooked up

**Comment by wsdjeg** [comment]
maybe it has been fixed

**Comment by rgrinberg** [comment]
Yup this is fixed in neovim master.

**Comment by wsdjeg** [comment]
:sob: but my issue is https://github.com/morhetz/gruvbox/issues/94
