### ISSUE TITLE
:Make does not open quickfix in Windows (gvim/vim)

### ISSUE THREAD

**Issue by bvnierop** [tpope/vim-dispatch#165]
Found when trying to use OmniSharp's test runner, reproduced with a small python file:

    from __future__ import print_function
    import sys

    print('hello, world!')
    print('hello, error!', file=sys.stderr)

`:Dispatch py test.py` opens quickfix with expected output
`:let &l:makeprg='py test.py' | :Make` does not open quickfix. After :Copen, quickfix does contain the expected output.

Surely, it's just me doing something wrong, but I haven't managed to figure out what that might be.

**Comment by tpope** [comment]
If you set `'makeprg'` by hand you also have to set `'errorformat'` by hand.

**Comment by bvnierop** [comment]
Got it. Found the offending part in OmniSharp and will fix it there. Thanks <3

Goes to show how little I know about Vim even after a few years :p
