### ISSUE TITLE
Displaying the executed command might cause hit-Enter prompt

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-dispatch#166]
The code at https://github.com/tpope/vim-dispatch/blob/eb3e564fb1edfee09fe6aeb57f3388e273da72c8/autoload/dispatch.vim#L218-L219 might trigger a hit-enter prompt (when it's too long / in a small window).

This causes issues, e.g. https://github.com/radenling/vim-dispatch-neovim/pull/4.
But even after fixing this, it seems like there's an issue where the tempfile from vim-dispatch-neovim only contains 10 empty lines, probably because the terminal window is still considered to be empty at that point (because of the hit-enter).

What do you think about only doing this `echo` if `&verbose` is > 0?

Is there some other way to handle this better?
As a workaround I could imagine cropping the line to something that fits into `cmdheight`, but that then seems to be more an issue to tackle at the core / vim.

/cc @radenling

**Comment by tpope** [comment]
I think your workaround is the way to go: Truncate `a:request.expanded` such that the entire line fits within `&cmdheight * &columns`.

**Comment by blueyed** [comment]
Given the fix for https://github.com/radenling/vim-dispatch-neovim/pull/4 I could imagine that it's a similar thing, where some commands fail with "not allowed here" or something similar, and could be replaced maybe?

btw: the "Success:" message simply does not get displayed if the window is too small - instead of the hit-enter prompt?! (https://github.com/tpope/vim-dispatch/blob/83e68d9fb1d60e8cdefe1e16e61b5dbf7d4f5680/autoload/dispatch.vim#L808)

After all, this should happen with `echo` in general, no?

**Comment by blueyed** [comment]
> After all, this should happen with `echo` in general, no?

It works for displaying the cmd also when `redraw` is used after it.

`dispatch#complete` is called by dispatch-neovim in the `on_exit` handler, which appears to make Vim truncate the message automatically (with `T` in `'shortmess'`).
It would be nice if this mechanism could be triggered by vim-dispatch also for the case at hand.

**Comment by blueyed** [comment]
A shorter/simpler approach would be to just call `:redraw` after the `echo` (which might be changed to `echom` then): this would avoid the hit-enter prompt and just not display the message.

But still: it would be better to find a to trigger Vim's auto-truncation (in the middle of the string).

**Comment by tpope** [comment]
What constitutes "middle", even?

**Comment by blueyed** [comment]
The middle of the string..?!

I agree that it's better to have control over this as with my PR.

**Comment by yevhen-m** [comment]
Hey, how can I get rid of this 'Hit ENTER' prompt?

**Comment by yevhen-m** [comment]
Can somebody tell what the status of this issue?

**Comment by tpope** [comment]
Is the `-12` related to `'ruler'`, maybe?

**Comment by blueyed** [comment]
@tpope 
Might be - or something similar.  I do not have it set currently though.

**Comment by simlei** [comment]
I would very much love to see this feature implemented. Sometimes you just cannot avoid long call strings.
Best regards

**Comment by tpope** [comment]
I'm open to a "good enough" solution if someone wants to craft a PR.

**Comment by Konfekt** [comment]
Isn't https://github.com/tpope/vim-dispatch/pull/167 the way to go?

**Comment by tpope** [comment]
Needs conflict resolution but yeah, that certainly qualifies as "good enough".

**Comment by simlei** [comment]
I have that exact PR merged into my local fork which is 6 months old. Will review and post it soon.

**Comment by blueyed** [comment]
Rebased it.
Needs -13 (instead of -12) for me now.. :/

**Comment by petobens** [comment]
I've started using this but apparently cannot get (or didn't understand) the expected result. Consider the following minimal `init.vim`:
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/tpope/vim-dispatch
filetype plugin indent on
```
Now, as in the GIF, open nvim in a small window (~60 columns) and do:
1. `:e a_very_very_very_very_very_very_very_long_file_name.sh`
2. `:let &makeprg='sh ' . expand('%')`
3. `:Make!`
After 3. I see the `Press ENTER...` message. I thought this pr prevented this (but I might be completely missing the point)

![dispatch-length](https://user-images.githubusercontent.com/2583971/61975231-f294dd00-afbe-11e9-8e5f-74c4990fcd6d.gif)

**Comment by blueyed** [comment]
@petobens 
You can test it more easily with `:exe 'Dispatch! echo '.repeat('X', &columns + 100).'; sleep 2'` - there should not be a hit-enter when starting the job, but there is one with the success message (which is not being truncated).

**Comment by tpope** [comment]
Oh I didn't look too closely. The success message is way more important to truncate than the start message because that one interrupts what you are doing.

**Comment by blueyed** [comment]
Ok - I've thought this should be kept verbatim, since it is available in `:messages`.
Should the same method used for both of them then?

**Comment by Konfekt** [comment]
Truncating the success message was what lead to resurrecting this issue; I didn't occur to me that the PR only truncates the start message.

**Comment by tpope** [comment]
I think we should probably stop using `:echomsg`? I think my rationale was that we should add it to messages because you might miss it, but it's not like people proactively check `:messages`, and the truncation thing is far more important.

**Comment by blueyed** [comment]
It could still use `:echom` there (with the truncated message).

**Comment by tpope** [comment]
Nah :echo is fine, truncated message would be a bit weird.

**Comment by blueyed** [comment]
Looked into this now: it does not use `echom`, but only `echo` in both cases.
`v:echospace` can be used in newer Vim.
Do you want to keep the existing method for older Vims?  (and also apply it to success messages then)

> Nah :echo is fine, truncated message would be a bit weird.

Do you mean truncated messages are weird in the history, or that they should not be truncated in general?

Note that without `echom` they might get lost actually, due to the resizing/redrawing (when using "tmux" at least).  For that it might be useful to have them available in `:mess` then, even if truncated.

**Comment by tpope** [comment]
I mean truncated messages are weird in history. When Vim does it, it puts the full message in history, even if it displays a truncation, but I don't think there's any way we can do the same.

The purpose of the message is to alert you when the job is done. Its historical value is extremely low, so I say switch from `echomsg` to `echo`.

**Comment by mvanderkamp** [comment]
Just popping in to say I find `echomsg` very useful to confirm whether a command succeeded! Would an option to use `echomsg` be acceptable? Happy to work on a PR, but would like to hear whether it would have a chance of merging first.

**Comment by tpope** [comment]
Building from my "truncated messages are weird in history" premise, I'm not going to add a "put a weird message in my history" option. Find a way to fix that problem and we can talk, or even better, please investigate putting into the quickfix title, after the `(tmux/12345)` indicator, as that seems like the perfect place for it.

**Comment by tpope** [comment]
I think 250ea269e206445d10700b299afd3eb993e939ad resolves this.
