### ISSUE TITLE
Feature Request: On tmux, zoom to debugger pane

### ISSUE THREAD

**Issue by filipegiusti** [tpope/vim-dispatch#170]
Simple use case, I'm testing and when I add a `debugger` I want vim-dispatch open the tmux pane zoomed.

Is that in the scope of the project? Should it be a flag or should we allow any sort of arguments when creating the tmux pane?

**Comment by tpope** [comment]
Not sure about scope but I think the more pertinent issue is it's probably not possible at all, since that would in theory prevent the resize event from firing on exit. When I want to use a debugger I generally switch to `:Start` instead.

**Comment by filipegiusti** [comment]
In my case using `:Start` wouldn't be good, because I wanna start the debugger in the middle of a test case. However I want this to happen only when there is a debugger in the middle of a test case, most of the time tests run without it.

I only started using tmux recently, so I don't have any idea if that's possible, as your guess is that it isn't, I'll close the issue and maybe some day in the future I look into it.
