### ISSUE TITLE
tmux handler: using custom tmux_session does not poll/complete

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-dispatch#171]
I am trying to use a custom `g:tmux_session` (another tmux instance on another screen), but `dispatch#tmux#poll` is not called (because there's no VimResized event (https://github.com/tpope/vim-dispatch/blob/fc8d1e68cd58fb3ffdd56109bf855cda92b10b70/autoload/dispatch/tmux.vim#L122)), and therefore `dispatch#complete` also is not.

I am aware of https://github.com/radenling/vim-dispatch-neovim.git, but would like to use tmux in this case explicitly.
Would hooking into `CursorHold` be an option here?  Or should support for this (background polling) be added to `dispatch-neovim`?

Manually calling `dispatch#tmux#poll()` works.

**Comment by tpope** [comment]
Believe me I never would have bothered with `VimResized` if `CursorHold` was an acceptable solution. I'd rather disable foreground builds entirely if we can't use `VimResized` or something else reliable like `vim --remote`. Maybe Neovim has some other way it can be communicated back?

**Comment by blueyed** [comment]
> Maybe Neovim has some other way it can be communicated back?

Yes, Neovim has the concepts of jobs already.
That's what dispatch-neovim is using, but then uses a terminal window for this.

What's your opinion on supporting Neovim directly?
Where would I have to poke to get it integrated?

**Comment by blueyed** [comment]
Well, Vim has `job_start` by now also!

I've found this wrapper plugin https://github.com/prabirshrestha/async.vim/blob/master/autoload/async/job.vim.

**Comment by tpope** [comment]
Since `tmux split-window` returns immediately, I'm not clear on how `job_start` helps.

**Comment by blueyed** [comment]
It could be periodically restarted when polling.
