### ISSUE TITLE
Unable to use user installed shell

### ISSUE THREAD

**Issue by smutch** [tpope/vim-dispatch#179]
I use my own build of zsh on a system where I do not have root access.  This shell further depends on my own build of pcre.  When the shell is invoked by dispatch, a clean environment is is used and therefore my shell is unable to launch (due to not having access to pcre).

I've overcome this by adding a config variable `g:dispatch_extra_env_vars` (see https://github.com/smutch/vim-dispatch/commit/fc01b5e2955843353aba45f27e70a6e69ea26d59), however, I wanted to open an issue to ensure that there is no better way to do this and to see if this would be considered useful enough for a PR.

**Comment by tpope** [comment]
Could you handle this on your end using a wrapper script?

**Comment by smutch** [comment]
Sure.  I'd definitely be happy to try that as an alternative (I know this is probably a bit of an edge case).  

I'm not really sure how to do this though.  Would you have any high-level recommendations of how to proceed?  How would I write a wrapper to achieve this and use it?

**Comment by tpope** [comment]
I think you want something like

```sh
#!/bin/sh
MYVAR1=a MYVAR2=b exec myshell
```

**Comment by smutch** [comment]
Works like a charm.  Thanks for that!

**Comment by tpope** [comment]
I accidentally left out `"$@"` at the end of the last line.
