### ISSUE TITLE
After complete label not showing in tmux

### ISSUE THREAD

**Issue by JoshTGreenwood** [tpope/vim-dispatch#180]
**What I expected to happen:**
a "Success" message to appear in the status line after running a command that returned 0

**What happened:**
when run outside of tmux, expected behavior
when run inside tmux, no status message appears

**Gif showing the issue**
http://g.recordit.co/7iW1aEZkBN.gif

**Versions**
latest vim-dispatch
tmux: stable 2.2
vim: 7.4.769

**Comment by tpope** [comment]
The resize from the tmux window closing forces a redraw which erases the message. I've tried to fix this in the past and I don't think it's possible.
