### ISSUE TITLE
Dispatch + Tmux: Strange characters in Quickfix window

### ISSUE THREAD

**Issue by bdauria** [tpope/vim-dispatch#182]
I get some strange characters while trying to run a angular-cli command using Tmux and Vim Dispatch:
![dispatch-tmux-cli](https://cloud.githubusercontent.com/assets/8367233/17458670/08710c62-5c1a-11e6-8479-aff7a33248a5.png)

It looks like this when executed within the regular shell:
![cli-shell](https://cloud.githubusercontent.com/assets/8367233/17458669/08703a76-5c1a-11e6-9f30-8fcd36f345a7.png)

Any idea where that might be coming from?

Thanks.

**Comment by tpope** [comment]
The command in question is spewing them, along with color codes that we strip out. You can investigate stripping them out as well, or you can hack around it with `set shellpipe+=\ `, which causes dispatch to not use it's clever tmux pane capture trick.
