### ISSUE TITLE
E40: Can't open errorfile stalling dispatch

### ISSUE THREAD

**Issue by msprev** [tpope/vim-dispatch#185]
Dispatch was working great until recently. Now it fails on any invocation. I've tried reinstalling dispatch and tried to clear as much state as possible. But I still get the error message on `Make` or `Dispatch`

```
Error detected while processing function <SNR>4_lod_cmd[3]..dispatch#compile_command[110]..dispatch#complete[18]..<SNR>230_cgetfile:
line   19:
E40: Can't open errorfile /var/folders/n2/qr2dz65j5mjfrxd6pyqt0yww0000gp/T/vOCL2HD/11
Error detected while processing function <SNR>4_lod_cmd[3]..dispatch#compile_command[110]..dispatch#complete:
line   18:
E171: Missing :endif
```

The file `/var/folders/n2/qr2dz65j5mjfrxd6pyqt0yww0000gp/T/vOCL2HD/11` does not exist, so I'm not surprised that dispatch cannot open it. Is there some way to start a new errorfile or somehow clear dispatch's state so that it works again?

**Comment by tpope** [comment]
This error generally indicates an error spawning the shell. Can happen when using `fish`, or when you've tweaked shell settings, or when there's a syntax error in your command.

**Comment by msprev** [comment]
Thanks. I'm using fish shell with iTerm. It was working fine until recently (past couple of weeks). Is there any workaround for using fish?

**Comment by msprev** [comment]
This fixed the issue for me: https://github.com/thoughtbot/vim-rspec/issues/87. What I missed before was to have `set shell=/bin/bash` in vim. Now working fine! Thank you!
