### ISSUE TITLE
Dispatch not using tmux in macOS Sierra

### ISSUE THREAD

**Issue by monokrome** [tpope/vim-dispatch#189]
Upon updating to macOS Sierra with Vim 8, the tmux integration stopped working for me in iTerm2. I figured that maybe I needed to update things, so I updated all of my packages and the issue still remained.

I'm not sure if this is helpful / reproducible on other machines, but wanted to flag this in case it's an issue that others are seeing. Also, I'd be happy to help however I can! This project is awesome :)

**Comment by sloria** [comment]
This is possibly the same issue as #192. I would recommend upgrading to the latest tmux using `brew upgrade tmux --HEAD`.

**Comment by monokrome** [comment]
@sloria I'm actually on an older version of tmux but it seems to work fine now. Thanks for the suggestion! :)
