### ISSUE TITLE
Kill process opened with :Dispatch

### ISSUE THREAD

**Issue by aemonge** [tpope/vim-dispatch#190]
It would be cool to have the ability to kill a process opened with `:Dispatch node server.js`, such as `:KillallDispatch`

**Comment by tpope** [comment]
There is an `abort` branch which explores this. It probably wouldn't take much to bring it up to date.

**Comment by teoljungberg** [comment]
I've been using https://github.com/tpope/vim-dispatch/commit/14228deecd6fed7b229aba4f7e55fc3cf3a742e7 for the last couple of weeks, and it's been working well for me. All under the `tmux` adapter, worth noting.

Is it worth while integrating the `:AbortDispatch` command into `master`?

**Comment by tpope** [comment]
Definitely. Try the version living on the `job` branch, as I believe I tweaked it recently.

**Comment by nietaki** [comment]
For people like me, getting here from a google search:

`:AbortDispatch` is implemented and it works great :)
