### ISSUE TITLE
Malformed quickfix list with :Make + tmux 2.3

### ISSUE THREAD

**Issue by AndroidOatmeal** [tpope/vim-dispatch#191]
### Issue description

I recently began experiencing some really odd behavior with `:Make` and tmux, where the quickfix list seems to be missing seemingly arbitrary characters from the compiler output. Strangely, this malformation does not happen with regular `:make`. Here is an example:

I created a simple scala project and created a single, intentional compiler error.

Resulting full quickfix list with `:make`:
<img width="1275" alt="screen shot 2016-10-07 at 10 28 58 am" src="https://cloud.githubusercontent.com/assets/3051042/19199541/6204bf1e-8c79-11e6-8acc-84e33d2ac2ca.png">
The above quickfix list looks fine (the `errorformat` isn't correct for this compiler but that doesn't matter here).

Resulting full quickfix list with `:Make` + tmux:
<img width="1273" alt="screen shot 2016-10-07 at 10 29 46 am" src="https://cloud.githubusercontent.com/assets/3051042/19199597/9dcaa432-8c79-11e6-9540-d70676f7d773.png">

The malformations themselves are odd; I have noticed that the 'c' character often gets removed, but I haven't found any solid patterns yet.

### Notes

Vim version: 8.0.12
Tmux version: 2.3
Vim-dispatch commit: latest version on master, commit `a54f2c5`

To make sure this issue wasn't some side effect of my vim config, I reproduced this issue with a very minimal vimrc:
[minimal_vimrc.txt](https://github.com/tpope/vim-dispatch/files/516792/minimal_vimrc.txt)

Finally, here is the full raw error output, in case it helps:
[test_error_full.txt](https://github.com/tpope/vim-dispatch/files/516788/test_error_full.txt)

Thanks in advance for your time!

**Comment by toiffel** [comment]
This happens for me too with Vim 8 + tmux 2.3. Downgrading tmux to 2.2 solves the issue.

So I guess the problem is related to parsing output of tmux pane or somewhat else in tmux adapter.

**Comment by tpope** [comment]
Try with `:set shellpipe+=\ ` (with a trailing space).

**Comment by nramirezuy** [comment]
@tpope It did it for me. Perhaps it's worth adding to the README.

**Comment by AndroidOatmeal** [comment]
@tpope your fix works for me as well, thanks!

**Comment by toiffel** [comment]
@tpope Confirming, works for me too. Any chance to have this in the plugin itself?

**Comment by tpope** [comment]
Let's merge this into #192.
