### ISSUE TITLE
New vimscript error after :Mak completes, when not using tmux.

### ISSUE THREAD

**Issue by vectorstorm** [tpope/vim-dispatch#196]
In commits since (and including) yesterday's b982e5305fb940a2808c57a0a47bce6750a69309  (determined via `git bisect`), Dispatch has begun to spit out an error message after executing `:Mak<CR>` in a terminal vim that's not embedded within a tmux session:

    Error detected while processing function dispatch#compile_command[109]..dispatch#complete[17]..<SNR>43_postfix:
    line    2:
    E716: Key not present in Dictionary: handler.'/'.(!empty(pid) ? pid : '?') . ')'
    E15: Invalid expression: '(' . a:request.handler.'/'.(!empty(pid) ? pid : '?') . ')' -1

The build *does* complete successfully despite the error message;  the error message appears to be kicked only after the build completes, when Dispatch is trying to retrieve the build output.  In the event of an error, the quickfix list doesn't pop up, and if I bring it up manually, its contents haven't been loaded.

Potentially relevant details:  I'm running on Ubuntu 16.10, without tmux, and I'm using a custom makeprg value ("ninja -C build").  But not using tmux seems to be the important factor;  running vim inside tmux on this same setup makes everything work without errors.  Verified across 'st', 'urxvt', 'xterm', and 'gnome-terminal' terminals.

If you'd like, I can have a look to find the problem and submit a pull request;  I suspect it'll just be something simple that's been missed in the unusual "not running inside tmux" code path.  But I figured I'd report it first, just in case you already know the problem.  :)

**Comment by tpope** [comment]
Thanks for the bisect. I suppose adding the handler name to the success message means I need to name the unnamed handler.

**Comment by vectorstorm** [comment]
Confirmed:  all sorted now!
