### ISSUE TITLE
Running with docker-compose

### ISSUE THREAD

**Issue by willian** [tpope/vim-dispatch#198]
Hi! First of all, thanks for the amazing plugin :)

I'm using `vim-test` to run my tests from Vim using vim-dispatch. The command I'm executing is something like this:

```
:Dispatch docker-compose run --rm -T test bin/rspec spec/models/category_spec.rb
```

But, as you can see below it's not closing the result when my specs passed:
![Vim](https://d2ppvlu71ri8gs.cloudfront.net/items/3x2g1Z2s0V3U2J42302L/Screen%20Recording%202017-04-25%20at%2011.30%20PM.gif)

Do you know why is it happening? Is there something I should config on my end to make it working like if I'm running locally _(without docker-compose)_?

**Comment by tpope** [comment]
The default error format leaves the window open if any output was produced. The solution is to use the rspec compiler, which you should be able to achieve with a bit of config to ignore the docker part of the command.

```viml
if !exists('g:dispatch_compilers')
  let g:dispatch_compilers = {}
endif
let g:dispatch_compilers['docker-compose run --rm -T test'] = ''
```

**Comment by willian** [comment]
Thank you @tpope! It worked perfectly :)

**Comment by nomasprime** [comment]
@willian I'm hoping you can help as you seem to be the only other person that's filed an issue relating to Docker.

Did you ever get a bunch of escape codes in your output? If you did, what did you do about them?

**Comment by tpope** [comment]
Are you passing `-T`?

**Comment by nomasprime** [comment]
@tpope I've tried with and without. I've reverted back to local dev environment but can't get Dispatch working there either (see https://github.com/tpope/vim-dispatch/issues/291).

**Comment by tpope** [comment]
You definitely want `-T`, for the record, as it prevents pseudo-tty allocation which will cause some programs to output escape sequences even though we can't handle them.
