### ISSUE TITLE
Extra lines in Quickfix list

### ISSUE THREAD

**Issue by alexlafroscia** [tpope/vim-dispatch#199]
I'm seeing a slight different between the entries in the QuickFix menu based on running `:make` and then `:copen` vs. running `:Make`.  For context, the compiler is `eslint` with the following `errorformat`

```vim
CompilerSet errorformat=%f:\ line\ %l\\,\ col\ %c\\,\ %trror\ -\ %m,
      \%f:\ line\ %l\\,\ col\ %c\\,\ %tarning\ -\ %m,
      \%-G%.%#
```

From what I understand, the `%-G%.%#` should ignore all lines that don't match the other patterns and ignore them, which is what I want to do.

If I run `:make` and then `:copen`, I get the following (which is what it should look like)

![screen shot 2017-05-04 at 4 18 33 pm](https://cloud.githubusercontent.com/assets/1645881/25728660/5a4b24dc-30e5-11e7-84aa-627f38ecd0e4.png)

However, if I run with `:Make` instead, the QuickFix list pops open with the follow instead:

![screen shot 2017-05-04 at 4 19 29 pm](https://cloud.githubusercontent.com/assets/1645881/25728675/770e41da-30e5-11e7-9d98-4d84bd584132.png)

It seems like the extra output isn't be ignored when Dispatch loads the results into the list. Do you think this is an issue with the configuration of the `errorformat` that I'm using, or something in Dispatch?

**Comment by tpope** [comment]
Dispatch explicitly strips off the a trailing `,%-G%.%#`, because unlike with regular `:make`, you never get to see that output otherwise. You can force the issue by including it a second time.

**Comment by alexlafroscia** [comment]
Ahh, great. Thanks!
