### ISSUE TITLE
Dispatch output truncated to appx. 1000 chars per line

### ISSUE THREAD

**Issue by mellery451** [tpope/vim-dispatch#200]
I have some long lines in my compilation output (linking a big project) and I've noticed that lines longer than about 1000 chars are truncated in the quickfix window (might be 1024...). I'm not sure if this is a quickfix setting or something in the vim-dispatch processing of the lines. 

I'd appreciate any advice you can offer for getting this long lines of output to be kept without truncation.

**Comment by tpope** [comment]
It's a hard coded Vim limit. You can `` :split `=&errorfile` `` to look at the raw file, but other than that you're out of luck.

**Comment by mellery451** [comment]
this works - thanks for the info. I've also decided to pipe my build commands to `fold` which feels wrong, but at least prevents me from loosing output in the qf.
