### ISSUE TITLE
Completion for :Spawn different from the one for :!

### ISSUE THREAD

**Issue by shym** [tpope/vim-dispatch#202]
I ran into two issues with :Spawn’s completion.
1.  If the cursor is at '*' in `:Spawn * file`,  completion proposes (correctly) names for executables. But in `:Spawn a* file`, it suggests completions of filenames beginning with 'a' instead.
2.  The characters that should be escaped (I checked with spaces and semi-colons) in filenames don’t get escaped.

**Comment by tpope** [comment]
Escaping is easy enough. Positional parameters are really hard to get right. Hopefully my fix doesn't break something else.
