### ISSUE TITLE
Enable Dispatch only when in certain filetype

### ISSUE THREAD

**Issue by ajmwagar** [tpope/vim-dispatch#204]
I love Dispatch! it's great. But recently I have moved away from compiled languages other than C#. Is there a way to disable Dispatch when I am not in a .cs file? This would be great because Dispatch slows down my vim setup a toooooooooooooooooooon. Is there any way to only use it when I am in a C# File? Any help would be appreciated.

**Comment by tpope** [comment]
I don't understand. Dispatch sits in the background until you call `:Dispatch` or some other command. What's slow?

**Comment by ajmwagar** [comment]
I'm a dumbass. Wow. I am sorry to be a bother. closing! (Wrong plugin)
