### ISSUE TITLE
Dispatch runs program twice

### ISSUE THREAD

**Issue by vogler** [tpope/vim-dispatch#205]
Commit de1c879ee675b5e20e756700177cd9e7c3e9d27a introduced the problem for me, which sometimes led to corrupted pdfs.

Tested with Makefile
~~~
all:
	echo foo >> log
~~~
Before the commit, `log` only contained one line, now two.

Vim 8.0
tmux 2.5
iTerm 3.1.beta.5

**Comment by tpope** [comment]
Tried the simpler `:Dispatch echo foo >> log` and only got one line. You're using the `tmux` adapter?

**Comment by vogler** [comment]
Sorry, the problem is with `Dispatch!` only.
`:Dispatch echo foo >> log` gives me one line, `:Dispatch! echo foo >> log` two.
I'm currently using iTerm, but also get the problem with tmux (and plain Terminal.app).
