### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by i2133514** [tpope/vim-dispatch#206]
Not sure if I'm missing something here, but doing something that I thought would be basic:

    :Dispatch npm install

Jumps me to an empty screen, which then shows the output of the above command.  
I expected it to instead run in the split at the bottom (it does eventually do this - after the command has completed).

Have I misunderstood the purpose of this plugin?

**Comment by tpope** [comment]
In order to run in a split in the bottom you need to use an adapter like tmux.

**Comment by i2133514** [comment]
Are adapters a Vim concept, or just for vim-dispatch?
Is having tmux installed enough?

**Comment by tpope** [comment]
A dispatch thing, see `:help dispatch-strategies`. Typically you run inside of tmux but see the help for other possibilities.
