### ISSUE TITLE
Add a way for a task to call back using vim 8 "jobs"

### ISSUE THREAD

**Issue by shym** [tpope/vim-dispatch#210]
We could add another mechanism (beside GUI or VimResize) to allow running tasks to call back when they complete using a vim 8 job. This would enable using adapters for foreground tasks even when `remote-expr` is not available.
I was thinking about something like:
- mkfifo request.file.callback,
- run a new job that waits on that fifo (such as head), with dispatch#complete as its exit_cb,
- return `echo > request.file.callback` from `dispatch#callback`.

This would require an OS supporting FIFOs, I’m not sure how portable this is, but I imagine that vim is used GUI-less mostly on unix.
Would that make sense or do you think this is useless?

**Comment by tpope** [comment]
I like it. Can you cobble together some functional example code? Don't worry about integrating with dispatch.vim yet, just show me that all the low level pieces work.

**Comment by tpope** [comment]
Also, is this something Neovim can get in on too?

**Comment by shym** [comment]
Here is a small prototype, without getting into dispatch itself:

```vim
function! CallMe(arg)
    echo 'I was called with' a:arg
endfunction

function! InitCallBack(arg)
    let fifo = tempname()
    silent call system('mkfifo ' . shellescape(fifo))
    call job_start(['head', '-1', fifo],
                 \ {'in_io': 'null',
                 \  'out_io': 'null',
                 \  'err_io': 'null',
                 \  'exit_cb': { ... -> CallMe(a:arg) } })
    echo 'Call me back with "echo >' fifo . '"'
endfunction
```

Possible alternative: use only one fifo for all the callbacks, running a loop of `head` and reading the `arg` on the standard output of that job. I think this version is simpler and so I’d suppose it a bit more robust.

I have never tried Neovim, but for the very basic use of `job_start` this relies on, I suppose Neovim’s `jobstart` could be used pretty much in the same way.

**Comment by tpope** [comment]
Pushed a prototype to the `fifo` branch.

Anyone know if FIFOs work on Cygwin or WSL? It would be nice not to leave anyone out in the cold.
