### ISSUE TITLE
Escape characters intermittently show up

### ISSUE THREAD

**Issue by chrisjohnson** [tpope/vim-dispatch#212]
Let me preface by saying I am using vim-grep which uses :Dispatch to run the grep command by setting makeprg to grep (or ag, or git grep). I'm running vim inside tmux

I should also clarify that I've got a binding, `,k`, which runs :Grep on the last searched word

`nnoremap <leader>k :Grep "<C-R>/"<CR>:cw<CR>`

Now here's a screencast of my problem in action. Note that I'm just literally running `,k` again and again here, not doing anything different from call to call: http://recordit.co/Bne2FI3AOP

I tried running this same setup outside of tmux and it never happens there, so my guess is this may be some sort of race condition or something relating to the tmux pane method of dispatching.

I think this is more relevant to vim-dispatch than vim-grep because vim-grep is basically just setting makeprg and errorformat and then letting dispatch handle the rest, but please let me know if my thinking is wrong. I could try to make a reduced test case that sets makeprg and errorformat manually without vim-grep at all

**Comment by tpope** [comment]
My first guess is your `.zshenv` has got some gross hack in it that tries to set the terminal title.

**Comment by chrisjohnson** [comment]
I'm using a vanilla zsh on OS X with a pretty much vanilla zprezto install. I disabled the auto-title feature with:

`zstyle ':prezto:module:terminal' auto-title 'no'`

I also temporarily disabled tmux's similar feature:

`set-option -g allow-rename off`

And following some advice I found, looked for title-setting characters in PS1/PROMPT as such:

`printf %q "$PS1" | grep -F '\\033'`

With no results.

Any other ideas how to confirm/disconfirm your theory?

**Comment by tpope** [comment]
`^[]1;` and `^[]2;` set the icon name (tab label) and title, respectively. *Something* is outputting them. Dispatch itself outputs them, although I wouldn't expect it to set the icon name to "tmux" unless vim-grep is doing something weird. On that note, I can't find any plugin by that name.

The reason it's intermittent is a race condition between the escape code output and our invocation of `tmux pipe-pane`.

**Comment by chrisjohnson** [comment]
https://github.com/teoljungberg/vim-grep but actually I forked it to fix a few bugs and to detect which grepprg to use for each call rather than detecting once then running: https://github.com/chrisjohnson/vim-grep

Anyway, I deleted vim-grep, I deleted every local zsh config I have, returning me to a completely vanilla zsh install (or whatever is vanilla from homebrew). Also deleted .tmux.conf giving me a completely vanilla tmux config.

Then I copied the makeprg and errorformat that vim-grep was setting and set them manually:

`set makeprg=git\ --no-pager\ grep\ -n\ \"nocompatible\"`

`set errorformat=%f:%l:%m`

And here's the result: http://recordit.co/Gf4S7ah0xZ

In fact now the issue is no longer intermittent, it's just happening every time.

I ran the grep command that it's running to confirm the output looks ok and here's what I get:

```
CMMC02TN0LRG8WL% git --no-pager grep -n "nocompatible"
.vim/doc/project.txt:47:You must set 'nocompatible' in your |vimrc| file to use this plugin. You can
.vimrc:2:set nocompatible
```

So I'm a bit unsure here. I can't see what else might be configuring that on my end. If you have any other places to look as to what might be setting the title I'm game to inspect further and try to further reduce the test case

**Comment by chrisjohnson** [comment]
Just to confirm it wasn't also my local vim config I completely deleted .vimrc and .vim, cloned vim-dispatch as .vim in my home dir, and ran it again. Same results. I looked in /etc for zsh config files and nothing in there except some mac-zsh specific config that comes with the brew installed zsh.

**Comment by chrisjohnson** [comment]
Sorry to waste your time, but I just updated my vim-dispatch and the issue seems to have gone away, I just ran :Make 40 times consecutively and it didn't happen.

FWIW I was on commit 1c2abfc if you're at all interested. As soon as I switch back to that commit it starts happening again, and then when I go back to master it fixes.
