### ISSUE TITLE
Empty output when using Fish shell

### ISSUE THREAD

**Issue by kyleholzinger** [tpope/vim-dispatch#217]
I'm not sure if it's something that I'm doing or some config, but whenever I run any command with `:Dispatch`, the split is empty and doesn't show any output

**Comment by tpope** [comment]
Try in 2 or more adapters (tmux, screen, plain terminal, etc) and see if it's specific to one of them.

**Comment by kyleholzinger** [comment]
Ahh interesting, looks like it was an issue with the fact that I use fish. When I changed my default shell to bash it works @tpope

**Comment by dduan** [comment]
I can confirm this.

**Comment by AndreVolpi** [comment]
@tpope is there a fix to be able to use with fish and tmux?

**Comment by kyleholzinger** [comment]
@AndreVolpi I set my default shell for all of vim to bash and that fixed it! Try putting this in your .vimrc:

```vimscript
set shell=bash
```

**Comment by AndreVolpi** [comment]
Doing that makes dispatch open a new tmux window, which I understand was not the expected behavior.

**Comment by kyleholzinger** [comment]
Doing what? setting the shell to bash? @AndreVolpi

**Comment by AndreVolpi** [comment]
Yes, when I set Vim to use bash instead of fish, and I call dispatch, it opens a new window, instead of a new pane.

**Comment by jsatk** [comment]
This seems related to my issue here: 
https://github.com/tpope/vim-dispatch/issues/243
