### ISSUE TITLE
Target specific tmux session

### ISSUE THREAD

**Issue by Richard-Degenne** [tpope/vim-dispatch#220]
I don't know much about tmux, but is it possible to have builds run in an existing session? I have a separate session for tests and would like to see the output there too.

**Comment by jadamwilson2** [comment]
Richard, did anything happen with this? I would like this as well. I have vim taking up one monitor, and a smaller terminal on another display for monitoring builds and tests.

**Comment by tpope** [comment]
https://github.com/tpope/vim-dispatch/blob/ca88fd7bd3d58620c7bfd604e3ebfa71b9c5001d/doc/dispatch.txt#L157-L159 (which works outside of a GUI too).
