### ISSUE TITLE
:Make not parsing errors according to errorformat while :make does

### ISSUE THREAD

**Issue by sunnypp** [tpope/vim-dispatch#222]
Here is my `&errorformat` and `&makeprg`
`let &errorformat="%.%#at %[%^/]%\\@=%f line %l.%m"`
`let &makeprg='ssh -t -t ... "cd ...; prove %"'`

When using `:make` the errorformat worked, capturing the file, line number, and a multi-line message.  That doesn't work with `:Make` --  `:Make` is returning each line as a separate error. Just random guessing, will it be related to how `:make` is handling returned `^M` from `ssh` (because when `:make` "works" it shows a lot of `^M` but not with `:Make`?  Also, even in the "All test successful" case, `:make` would populate the quickfix list while `:Make` does it better and nothing goes into it.  What may be happening behind the scenes?

Mmm.. I have checked some other issues here, and I'm not using `%-G%.%#` nor pipes in my `&makeprg`. By the way, my custom errorformat is for skipping files that have absolute path starting from root so it helps me filter out some irrelevant files.  Please kindly instruct me about ways to investigate further.  Many thanks in advance.

**Comment by tpope** [comment]
My first guess is the use of `-t -t`, forcing a pseudo-terminal without a real one, is wrecking all sorts of havoc, the exact nature of which probably varies from adapter to adapter.

**Comment by sunnypp** [comment]
Thanks Tim!  That's possible and I guess I have just run into the [XY-problem](https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem) myself... Sorry for raising this issue and I am happy using `:Make`.  I'll just try to tweak my `&errorformat` so that it works with `:Make` and deprecate `:make` in my workflow ;)

**Comment by artemave** [comment]
Hello!

I am having a similar issue - `:make` shows errors correctly while `:Make` does not - using tmux adapter.

```viml
autocmd FileType {javascript,jsx} set errorformat=%+A\ %#%f\ %#(%l\\\,%c):\ %m,%C%m
autocmd FileType {javascript,jsx} set makeprg=./node_modules/.bin/tsc\ -p\ tsconfig.json
```
`:make` output:
![image](https://user-images.githubusercontent.com/23721/49212116-8cb96c80-f3c1-11e8-936a-ce9e7a8fe8e0.png)

`:Make` output:
![image](https://user-images.githubusercontent.com/23721/49212309-05202d80-f3c2-11e8-8464-aed3d9983874.png)

 Could you please help me fix this?

Thanks!

**Comment by tpope** [comment]
Does it work with other adapters?

**Comment by artemave** [comment]
Good question! Just tried in a new iterm tab (no tmux) and `:Make` works as expected.

**Comment by tpope** [comment]
Try `:set shellpipe=2>&1\|tee` and see if the problem persists.

**Comment by artemave** [comment]
`:set shellpipe=2>&1\|tee` fixed the problem!

**Comment by artemave** [comment]
Yes! Very different:

![image](https://user-images.githubusercontent.com/23721/49255751-3a159a00-f42d-11e8-936c-bedd0921d9df.png)

**Comment by jsatk** [comment]
holy shit i've been looking for this damn solution for forever.

**Comment by tpope** [comment]
It works because the tmux adapter takes *any* change to the default as a sign that it should use it as is rather than doing pipe-pane shenanigans:

https://github.com/tpope/vim-dispatch/blob/d8bf968958f4bdc838321cceace52299f28ad750/autoload/dispatch/tmux.vim#L42

I didn't originally intend "remove the space" as a mechanic to disable the feature, but since it works, I am endorsing it until I figure out something better. I have some not fully formed ideas about how to disable pipe-pane on a per compiler plugin basis.

**Comment by jsatk** [comment]
Thanks 🙏.

**Comment by jsatk** [comment]
@tpope if it helps you debug at all i'm only seeing this output when I use Dispatch to run Jest (a JS test runner).
