### ISSUE TITLE
Dispatch does not recognize custom bash functions

### ISSUE THREAD

**Issue by parvus-mortalis** [tpope/vim-dispatch#224]
I have custom bash functions that are defined in `functions.sh`. I source this file inside of my `.bashrc`. After sourcing both the functions file and my bashrc, I run a custom function to open the current html file in Chromium using Dispatch. I receive the error:

```
line 38: open_chromium: command not found
```

**Comment by tpope** [comment]
`.bashrc` is only loaded by interactive shells. It's exactly the same as if you had called `bash -c open_chromium` or `:!open_chromium`. There are many solutions to this. The easiest and least error prone is to make `open_chromium` a shell script in your `PATH` instead.
