### ISSUE TITLE
:Dispatch not working for pylint, but :Make is

### ISSUE THREAD

**Issue by wreed4** [tpope/vim-dispatch#225]
When running `:Dispatch pylint %`, the errorformat is not set correctly.  I tracked the code through quite aways and found that it does find the correct compiler with all the correct information in it.  However, it ends up ignoring the makeprg in the compiler and just runs `!pylint %`.  

In contrast, setting `:compiler pylint` and running `:Make %` executes the `makeprg` from the compiler as expected, and therefore sets the correct errorformat and errors are useable.  

My understanding from both the docs and looking through the code is that `Dispatch` tries to find a compiler matching `program` and then adjusts `makeprg` accordingly.  While the first half of this seems to be working the second half does not.  

Did a little more digging.  It seems that `dispatch#compiler_options` sets `makeprg` correctly, but once it returns, `makeprg` is no longer set. I think I see why that is, but in this case, makeprg defines many variables which are not being kept when Dispatch is called.  Here is the compiler plugin I'm working with (it comes standard with neovim)

```vim
" Vim compiler file
" Compiler:	Pylint for Python
" Maintainer: Daniel Moch <daniel@danielmoch.com>
" Last Change: 2016 May 20

if exists("current_compiler")
  finish
endif
let current_compiler = "pylint"

if exists(":CompilerSet") != 2		" older Vim always used :setlocal
  command -nargs=* CompilerSet setlocal <args>
endif

CompilerSet makeprg=pylint\ --output-format=text\ --msg-template=\"{path}:{line}:{column}:{C}:\ [{symbol}]\ {msg}\"\ --reports=no
CompilerSet errorformat=%A%f:%l:%c:%t:\ %m,%A%f:%l:\ %m,%A%f:(%l):\ %m,%-Z%p^%.%#,%-G%.%#
```

Any thoughts?

**Comment by tpope** [comment]
`:Dispatch` sets `'errorformat'` to the one found in the compiler plugin, but runs the command you give literally. So you would have to call `:Dispatch pylint --output-format=text --msg-template="{path}:{line}:{column}:{C}: [{symbol}] {msg}" --reports=no %`, or `:Dispatch pylint -f parseable %` which seems to have a similar enough effect without so much typing.

Unfortunately dispatch.vim does not provide a command that does what you are looking for, "invoke this compiler plugin with these additional arguments", but it would be easy enough to create your own if you so desired. Personally, I'd just set the default dispatch for Python files:

    autocmd FileType python let b:dispatch = 'pylint -f parseable %'
