### ISSUE TITLE
Option to immediately open quickfix

### ISSUE THREAD

**Issue by allopislozano** [tpope/vim-dispatch#226]
Hi everyone!

My compile times are usually slow   (~ 1-2minute) or, when I modify headers it can go up to 5-10min. I love this plugin but it'd be awesome if I could somehow get immediate feedback on the compilation, or at least as soon as the first error appears.  Other alternative would be to not clear the results of the quickfix until you have a new result.  Is this possible?

Thanks a lot and thanks for your awesome plugins!!  ;)

**Comment by tankorsmash** [comment]
Semi-related, and I can make a new issue, but I'm trying to open the quickfix immediately after I run :Make in a single command, but the `:Make` command swallows the pipe after:

`:Make \| Copen` doesn't `:Copen` anything. Once I do `:Copen` manually, it shows: 

```
|| 'Copen' is not recognized as an internal or external command,
|| operable program or batch file.
```

Seems like `:Make` is passing everything to the makeprg  (in my case, msbuild.exe on Windows).

**Comment by tpope** [comment]
You can also do `:exe 'Make'|Copen`.

**Comment by tankorsmash** [comment]
Oh very cool, thanks!

**Comment by pbnj** [comment]
> I have great aspirations for live updating in the near future, which could enable opening when the first error appears.

Correct me if I'm wrong, but I think this would solve the problem of vim getting hung/blocked when it tries to load 100K+ results from a Dispatch call (e.g. `:Dispatch rg --vimgrep "error" kubernetes/`)

**Comment by tpope** [comment]
Live updates have been implemented in the form of the job adapter. But if you have 100K+ results pouring in, I wouldn't expect any miracles. Vim will still block if parsing the results is the bottleneck.

**Comment by tpope** [comment]
And I guess that means we can close this.
