### ISSUE TITLE
:Start used to open new terminal, now throws x11? error

### ISSUE THREAD

**Issue by Levara** [tpope/vim-dispatch#227]
Hi, is it possible that there is a bug here?

https://github.com/tpope/vim-dispatch/blob/c5b1bbe1662d76c0aa9f6d325c3fb1b8db62ba02/autoload/dispatch/x11.vim#L42

It seems to me that this line adds terminal command to system call twice. If i run vim with `TERMINAL=xterm vim` than after calling :Start the command to run will be `xterm xterm -e whatever_i_called.py &`

I tried removing the second `a:terminal` from `dispatch#shellescape` and :Start works as before. 

If I'm not mistaken these changes are result of https://github.com/tpope/vim-dispatch/pull/223

I think the resulting line should either be:
`call system(dispatch#shellescape(a:terminal, &shell, &shellcmdflag, command). ' &') `
or 
`call system(a:terminal . ' ' . dispatch#shellescape(&shell, &shellcmdflag, command). ' &') `

I don't know which version would be better.

My setup is fully up-to-date Archlinux with Plasma5 and konsole as terminal.
The error shows up after latest vundle update on both nvim and vim8.

Thanks.

**Comment by tpope** [comment]
Exactly correct.
