### ISSUE TITLE
Quickfix list for Rspec removes new lines

### ISSUE THREAD

**Issue by jackkinsella** [tpope/vim-dispatch#228]
When I'm in a spec file and I run `:Dispatch %` or `:Dispatch rspec %` I get output that scrolls waaaay out east.

![screen shot 2018-03-01 at 20 52 01](https://user-images.githubusercontent.com/151206/36866388-72a96fc6-1d92-11e8-900c-26e53f274e27.png)

Here's what the same test outputs on the command line:
![screen shot 2018-03-01 at 20 52 29](https://user-images.githubusercontent.com/151206/36866425-8a043412-1d92-11e8-8e15-84e85116835d.png)

I'm using macos 10.13.2 and got the same results in vim 8.0 and neovim 0.2.2, and these horizontal tendencies persist no matter whether I use iTerm, the built-in Terminal or TMUX.

**Comment by tpope** [comment]
Vim's built-in `compiler/rspec.vim` does this deliberately. The quickfix *list* was designed to be a terse list of errors, not a verbatim capture of output. When shown in the quickfix *window*, it can get a bit ugly, particularly when you have long absolute paths and verbose RSpec chatter, but for features like `:cnext`, it works perfectly, showing you the full message as you jump between errors.

Maybe [ditching the "Failure/Error:" label](https://github.com/vim-ruby/vim-ruby/commit/dd3b785fed7b8bd761fbd413a659fcfd00f86e07) will bring things back into the realm of acceptability for you. If you still insist on a raw output capture, try forcing it to use the Rake `'errorformat'` instead:

```vim
if !exists('g:dispatch_compilers')
  let g:dispatch_compilers = {}
endif
let g:dispatch_compilers['rspec'] = 'rake'
```

**Comment by jackkinsella** [comment]
Many thanks — the `rake` compiler did exactly what I was expecting!
