### ISSUE TITLE
Question: Detect already running task?

### ISSUE THREAD

**Issue by yangmillstheory** [tpope/vim-dispatch#233]
```vim
augroup python
  autocmd!
  autocmd BufWritePost *.py <buffer> call <SID>TryMakeTest()
augroup END

function! s:TryMakeTest() " {{{
  if !exists('b:has_test_target')
    let b:has_test_target = filereadable('Makefile')
          \ && match(readfile('Makefile'), 'test:') != -1
  endif
  if b:has_test_target
    " vim-dispatch is a dependency
    Make test
  endif
endfunction
```

This works great, except when I save while `Make test` is already running, it kicks off another job (in tmux, this amounts to two stacked panes). I'm wondering, what do you think is the appropriate thing to do here? 

I don't think this is bug in vim-dispatch, just wondering if there's a better UI we can present.

BTW thanks for all your OSS; you're awesome :).

**Comment by tpope** [comment]
Use `dispatch#request()` to get a dict for the most recent dispatch. Check `empty(request) || dispatch#completed(request)` to find out if it's safe to run: either no dispatch has happened, or the most recent dispatch finished.

**Comment by yangmillstheory** [comment]
Thanks. Feel free to close :)

**Comment by yangmillstheory** [comment]
Actually it makes sense to close this, because it solves the issue.

```vim
function! s:TryMakeTest() " {{{
  if !exists('b:has_test_target')
    let b:has_test_target = filereadable('Makefile')
          \ && match(readfile('Makefile'), 'test:') != -1
  endif
  if b:has_test_target
    " vim-dispatch is a dependency
    let req = dispatch#request()
    if empty(req) || dispatch#completed(req)
      Make test
    endif
  endif
endfunction
```

**Comment by yangmillstheory** [comment]
Does the approach mentioned in https://github.com/tpope/vim-dispatch/issues/233#issuecomment-381024689 work for background tasks as well (e.g. those launched with `Make! test`)?

**Comment by tpope** [comment]
You can additionally check `filereadable(request.file '.complete')`. I thought `dispatch#completed()` checked that but I guess not.

**Comment by yangmillstheory** [comment]
I think that file can be readable even without the task being completed (it looks like it's touched before spawning the process, and the status code is written to it in `dispatch#complete`). So I think we'd have to try to read a line from the file for the check instead. 

Does that sound right?

**Comment by tpope** [comment]
That does not sound right, no. The plugin itself does the same `filereadable()` check.

**Comment by yangmillstheory** [comment]
https://github.com/tpope/vim-dispatch/pull/234
