### ISSUE TITLE
nremap docs are slightly confusing (or wrong) + dispatch should have an option to disable all mappings

### ISSUE THREAD

**Issue by Julian** [tpope/vim-dispatch#238]
Some of the new mappings conflict with some of my own.

`:h dispatch-maps` says

```
Use an empty string as the value to disable the map or maps entirely
```

which in retrospect appears to mean that I can do e.g.

```
let g:nremap = {"m": "", "'": ""}
```

as the example showed, but what I actually wanted to do (and tried to do) was

```
let g:nremap = ""
```

thinking it meant "use empty string to disable everything".

But that just produces some cryptic spam of

```
E715: Dictionary required
E715: Dictionary required
E715: Dictionary required
E715: Dictionary required
E715: Dictionary required
E715: Dictionary required
E715: Dictionary required
E715: Dictionary required
E715: Dictionary required
E715: Dictionary required
```

as dispatch assumes it's a dict.

**Comment by tpope** [comment]
You're not the first to be confused so I'll tweak the wording. What maps do you have that conflict? Since maps in this plugin are a bit of a frivolous extra, I am very interested in minimizing out of the box conflicts.

**Comment by Julian** [comment]
For metThe `<operator><CR>` and `<operator><Space>` ones are particularly common ones for conflict I think. I've got mappings on a bunch of those.

**Comment by tpope** [comment]
None of these are operators in the Vim sense. I assume based on your config excerpt you mean `m` and `'`?

**Comment by Julian** [comment]
Sorry, yeah, meant to just say "key". Those two.

**Comment by Julian** [comment]
Y'know what though! I think I ran into trouble back when this was mapped to `d<CR>`, which it looks like you already [changed](https://github.com/tpope/vim-dispatch/commit/e052da08c84f34d105fb57d7e0ade203dee7278c) -- I do actually have a `m<CR>` mapping too, but I use it a lot less often.

(The ' mapping I don't care about).

**Comment by tpope** [comment]
Alright, sounds like these mappings are still pretty safe.
