### ISSUE TITLE
:Make opens iTerm tab

### ISSUE THREAD

**Issue by geratheon** [tpope/vim-dispatch#240]
Right now `:Make` opens a new iTerm-Tab for building instead of running the build directly in the foreground.

You can recreate this behaviour with `vim --noplugin`, `:packadd vim-dispatch` and a simple `:Make`. (On Vim 8.0.1633 with the latest head e009487)

**Comment by tpope** [comment]
This is deliberate change made possible by the addition of job support to Vim 8. I take it you don't like it?

**Comment by geratheon** [comment]
If you have more than one tab open (with Vim in the first) it jumps to the last one after the build is complete. While I don't have a problem with building inside a tab, it's really annoying to not switch back correctly.

**Comment by tpope** [comment]
Good point. We shouldn't be focusing the new tab at all really. Try the latest and see if it improves the experience for you.

**Comment by geratheon** [comment]
I wouldn't say we shouldn't focus the new tab, since the documentation states "`:Make` dispatches a build in the foreground".

The latest build works for me, but it does not run it in the foreground (and so the bang is obsolete).

**Comment by tpope** [comment]
"Foreground" builds in Dispatch should be visible but not focused. When those are in conflict, "not focused"  takes precedence. Ideally we'd use an iTerm split instead but I'm not up for implementing that.

**Comment by geratheon** [comment]
That's fair, thanks!

**Comment by tpope** [comment]
Job support - coming after the next stable release - will probably render this obsolete anyways.
