### ISSUE TITLE
Quickfix not spanning the whole bottom in presence of vsplits

### ISSUE THREAD

**Issue by allopislozano** [tpope/vim-dispatch#242]
With the latest version (f708ce5)  I open a vertical split and launch a compilation with :Make and the quickfix is placed below the right column, instead of spanning the whole bottom. It looks like a bug, since I see that s:cwindow in dispatch.vim always tries to do :botright cwindow.  I don't know why it fails to place it spanning the whole bottom.

By the way if I close the incorrectly placed quickfix and issue  :botright cwindow   I get it spanning the whole bottom.

Im using Gvim 8.0,  no tmux, so the compilation process is shown in a separate xterm. In non gui vim I get the same bug.

**Comment by tpope** [comment]
Does it work as expected on da5562f12795c9a8eaf346573af2876300048ca4?

**Comment by allopislozano** [comment]
I have just checked and no, the behaviour is also wrong on that revision

**Comment by tpope** [comment]
If you bisect to the breaking commit perhaps I can figure out what's going wrong. It works as expected on my setup.

**Comment by allopislozano** [comment]
I found the issue, I had these lines in my .vimrc:
```

" Automatically open, but do not go to (if there are errors) the quickfix /
" location list window, or close it when is has become empty.
"
" Note: Must allow nesting of autocmds to enable any customizations for quickfix
" buffers.
" Note: Normally, :cwindow jumps to the quickfix window if the command opens it
" (but not if it's already open). However, as part of the autocmd, this doesn't
" seem to happen.
autocmd QuickFixCmdPost [^l]* nested cwindow
autocmd QuickFixCmdPost    l* nested lwindow
```

I am not sure where they came from or exactly what they do... but removing them fixes the issue
