### ISSUE TITLE
Could Spawn[!] with no argument use b:start?

### ISSUE THREAD

**Issue by urbainvaes** [tpope/vim-dispatch#244]
Since `Spawn` is "like `:Start`, but always spawns a new process rather than focusing an existing one", wouldn't it make sense for it to use `b:start`? 

Example use case: I launch a script using `:Start<cr>`, change it a bit, and then want to run the modified version in a different shell without interrupting the first run.

This plugin is a pleasure to use, by the way, thank you!

**Comment by tpope** [comment]
Not unreasonable but conflicts with my own goals. I'd be more inclined to add a `:Start -nomanage` or something, but it's also easy enough to map `:exe 'Spawn' get(b:, 'start', '')<CR>` that I'm inclined not to bother.

Also note if you set `b:dispatch`, you can call `:0Spawn` or `:0Start` to run it with the desired semantics. My own vimrc currently does that for anything with a `#!` line, so I can pick among the 3 commands depending on my needs.
