### ISSUE TITLE
Running zsh custom functions with Dispatch

### ISSUE THREAD

**Issue by mananaBanana** [tpope/vim-dispatch#245]
Hi,
I use `cmake` for building my projects and all the build files are in a directory one level above src/. I have a custom function defined in my `.zshrc` and `.zshenv` which takes care of both cmake and compilation (among other things). 
I used to call this function using `:!` but now I want to do the same with `:Dispatch`. The usual `:Dispatch make -C build` seems to work all right. When I run `:Dispatch bld` (my custom function), it opens a `tmux` split and returns Success but nothing really happens. 
I want to avoid rewriting the function in `.vimrc` and would like to know what's causing this and if there is a workaround.
Thanks

**Comment by tpope** [comment]
Move your function to a script in `$PATH`. The reason it works with `:!`is you `:set shellcmdflag=-ic`, forcing `.zshrc` to load in a non-interactive shell.  This `-i` flag has other side effects and isn't supported by dispatch.vim.

**Comment by mananaBanana** [comment]
Actually, I haven't set the `shellcmdflag`. It was indeed causing problems with my other plugins and so I haven't been using it since. What I instead did was copy my `.zshrc` to `.zshenv` (following the discussion [here](https://unix.stackexchange.com/questions/113462/how-can-i-make-shell-aliases-available-when-shelling-out-from-vim/197135#197135)) and that made the function work fine using `:!`.
Anyway that I can make the same thing work with dispatch.vim?

**Comment by tpope** [comment]
I'm unclear what's going on then, as zsh loads `.zshenv` *everywhere*. You'll have to dig into the relevant adapter and see what's going on. I still highly recommend using scripts rather than functions for this sort of stuff, based on my own experience doing similar things.
