### ISSUE TITLE
Executing command after dispatch

### ISSUE THREAD

**Issue by ivangeorgiew** [tpope/vim-dispatch#246]
I want to execute a command after `Dispatch! git checkout someBranch` is done.
Notice that it is silent. Is there a way to do that?

**Comment by tpope** [comment]
You can tap into `autocmd QuickFixCmdPost cgetfile` for `:Dispatch`. `:Dispatch!` does not have any callbacks by design.

**Comment by justinmk** [comment]
`autocmd QuickFixCmdPost cgetfile` fires at the beginning of the `:Dispatch` , instead of the end.
 Should users listen for `VimResized` to handle the end of the dispatch?

**Comment by tpope** [comment]
I guess it does fire then, and on every `:Copen`, but it also fires at the end, correct? I imagine there's a conditional that would work, but not sure what it would be. Maybe we need another autocommand?

Definitely don't use `VimResized`, that's tmux only and will have tons of false positives.

**Comment by ivangeorgiew** [comment]
@tpope The thing is I don't want to receive a quickfix list when the task is complete, but I do want to update the tags file when the git branch change is done. Maybe there is an autocmd from fugitive that is fired at that time?

**Comment by tpope** [comment]
If you ignore the quickfix list, then you also have no way to tell when the command fails. Dispatch is a user interface, not an API, and I'm not really interested in giving you enough rope to hang yourself.

My honest recommendation is to just do it synchronously with `system()`, because `git checkout` is really fast in all but the biggest of repos.

**Comment by justinmk** [comment]
FWIW my use-case is simply that I don't want dispatch.vim to close the quickfix window, ever. I don't really see why it should ever do that, but I probably have tunnel-vision. Essentially this patch:

```diff
diff --git a/autoload/dispatch.vim b/autoload/dispatch.vim
index 436b98ce5626..15e8aac5edb2 100644
--- a/autoload/dispatch.vim
+++ b/autoload/dispatch.vim
@@ -880,7 +880,6 @@ function! dispatch#compile_command(bang, args, count, ...) abort
   let request.title = get(request, 'title', get(request, 'compiler', 'make'))
 
   call dispatch#autowrite()
-  cclose
   let request.file = dispatch#tempname()
   let &errorfile = request.file
```

**Comment by tpope** [comment]
This happens *before* the task starts, mainly because having a blank quickfix window directly above a live tmux pane looks confusing if not stupid. For the `job` handler which live updates, the quickfix window is immediately re-opened.
