### ISSUE TITLE
Decrease escaping of :Focus commands

### ISSUE THREAD

**Issue by teoljungberg** [tpope/vim-dispatch#247]
If I perform `:Focus :Dispatch` within a Rails app, using vim-rails, `:Dispatch` will perform the following command:

```
:Dispatch -dir=/path/to/project bin/rails `=rails\#buffer(1).default_task(v:lnum)`
```

Unsetting the focused dispatch with `:Focus!`, checking the resulting command that will be run:

```
Buffer default is :Dispatch -dir=/path/to/project bin/rails `=rails#buffer(1).default_task(v:lnum)`
```

---

The issue seems to be that `:Focus` tries to escape the input, from characters such as `#`.

**Comment by tpope** [comment]
Escaping is correct, it just needs to be expanded first.

**Comment by teoljungberg** [comment]
Thank you!
