### ISSUE TITLE
Unable to jump to single error

### ISSUE THREAD

**Issue by landersson** [tpope/vim-dispatch#249]
Apologies if this has been asked before or is not at all related to vim-dispatch.

I'm trying to use vim-dispatch with cargo (rust). My issue is that if there is only a single error, the cursor wont automatically jump to the location of the error in the source file, and using vim-unimpaired's [q or ]q (:cnext, :cprev) will just give me the error "No more items". I can still jump to the first(only) error by switching focus to the quickfix window and pressing enter, or running :cc 1, but that's a bit inconvenient. If there are multiple errors, using :cnext or :cprev works fine.

Is there a way to have ":Make" automatically jump to the first and single error, or at least make it possible to jump to a single error using [q or ]q?

**Comment by landersson** [comment]
I just realised that I can mostly work around this by using [Q, i.e :cfirst.

If would still be nice to have :Make automatically jump to the first error on synchronous builds though.

**Comment by tpope** [comment]
Your use of "synchronous" is confusing here, it's only synchronous if you're using an unsupported setup. If that's what you're doing, you may as well use `:make`.

**Comment by landersson** [comment]
Ok, that makes sense. I was probably a bit mistaken about the main purpose of vim-dispatch. The problem that I originally wanted to solve was getting coloured error messages in quickfix, but I've realized vim-dispatch, even with a :terminal as an adapter, wont help me with that. Still a very useful plugin though. I'll close this issue.
