### ISSUE TITLE
:Dispatch does not revert makeprg after running

### ISSUE THREAD

**Issue by gpanders** [tpope/vim-dispatch#254]
I am not sure if this is a bug or a misconfiguration on my part. I wrote a custom compiler for the `clang-tidy` tool and have the following in my vimrc:

`autocmd FileType c,cpp let b:dispatch = 'clang-tidy -quiet %:S'`

Running `:Dispatch` from a C++ buffer works as expected; however, afterwards, `set makeprg?` still returns `clang-tidy -quiet %:S` and further invocations of `:Make` re-runs clang-tidy instead of running the default make program (in this case, just plain old `make`).

Steps to reproduce:
1. Open my C++ file
2. `set makeprg?` returns `make`
3. Run `:Dispatch`
4. `set makeprg?` returns `clang-tidy -quiet %:S`

My custom compiler is located in `~/.vim/compiler/clangtidy.vim` and has the following contents:
```vim
if exists('current_compiler')
  finish
endif
let current_compiler = 'clangtidy'

CompilerSet makeprg=clang-tidy\ -quiet\ %:S
CompilerSet errorformat=
      \%-G%*\\d\ %s\ generated.,
      \%-GError\ while\ processing\ %f.,
      \%E%f:%l:%c:\ fatal\ error:\ %m,
      \%E%f:%l:%c:\ error:\ %m\ [%s],
      \%W%f:%l:%c:\ warning:\ %m\ [%s],
      \%I%f:%l:%c:\ note:\ %m,
      \%-Z%p%^,
      \%C%.%#
```

**Comment by tpope** [comment]
This shouldn't happen. Try disabling other plugins as they may be engaging in buffer related shenanigans that cause the restore to happen in the wrong window.

**Comment by gpanders** [comment]
It appears the culprit was this line:
```vim
au QuickFixCmdPost [^l]* cwindow
```

Removing that fixes the issue.

**Comment by gpanders** [comment]
Reopening because unfortunately I still see this issue without that autocmd but when [romainl/vim-qf](https://github.com/romainl/vim-qf) is installed and `g:qf_auto_open_quickfix = 1`. Is this something that can be resolved on vim-dispatch's end, or is auto-opening the quickfix list fundamentally incompatible in some way?

**Comment by tpope** [comment]
A simple blacklist like that is asking for trouble. Use a whitelist like `make*,grep*` or whatever you actually need.
