### ISSUE TITLE
:Make does not update the buffer when the command is writing the file

### ISSUE THREAD

**Issue by Axnyff** [tpope/vim-dispatch#255]
Hello,
first of all thanks for this plugin ( and many others).

I'm trying to replace plain old `:make` with `:Make`but I have one issue, the buffer is not auto uploaded when the file has been written too.

For instance, if I'm using `prettier --write` or `eslint --fix`, I'd like my buffer to be autoupdated.

At best, I can make it work as soon as I move in the buffer with autocommands like this but it's not ideal:

    autocmd FocusGained,BufEnter,CursorHold,CursorHoldI ?* if getcmdwintype() == '' | checktime | endif

I tried a couple of plugins to fix the focus-events between vim and tmux but it didn't seem to change anything (https://github.com/tmux-plugins/vim-tmux-focus-events and https://github.com/sjl/vitality.vim)
Is there a better way to do this?

It seems to work with `vim -u NONE` and `:make` with  `set autoread` and `set autowrite` 

Thanks in advance

**Comment by tpope** [comment]
Modifying an open file asynchronously seems especially perilous, but I see no reason not to `:checktime` anyways in the event it does happen.

**Comment by Axnyff** [comment]
This is working perfectly, thanks a lot!
