### ISSUE TITLE
Dispatch! triggers QuickFixCmdPost but hasn't updated QuickFix

### ISSUE THREAD

**Issue by SevereOverfl0w** [tpope/vim-dispatch#256]
I use romainl/vim-qf to auto-open QuickFix when the QF contains anything valid. I'm using `:Dispatch! git push` in vim to do a push, and on completion it pops open the QuickFix but with the old data in it, even when there's no failure.

I'm not sure where to fix things for this, maybe this should actually be changed in romainl/vim-qf?

**Comment by tpope** [comment]
It fires `QuickFixCmdPost` twice: once [immediately after starting](https://github.com/tpope/vim-dispatch/blob/916b8d5dbffca021d0e9c3476f0d1992e7491e32/autoload/dispatch.vim#L768) with a nonstandard `dispatch-make` type, which can be used to for things like restoring options, and once [when the results are loaded](https://github.com/tpope/vim-dispatch/blob/916b8d5dbffca021d0e9c3476f0d1992e7491e32/autoload/dispatch.vim#L1084) with the standard `cgetfile` type, which is for use cases like this (but we already open the window so this particular use isn't necessary). It appears that vim-qf targets [literally every `QuickFixCmdPost` event](https://github.com/romainl/vim-qf/blob/master/plugin/qf.vim#L64-L65), which isn't compatible with our more nuanced uses. Instead, it should whitelist the particular commands it is actually targeting: `make,grep,grepadd,...`.

**Comment by justinmk** [comment]
Should this be documented?

**Comment by tpope** [comment]
It's hard to argue against documentation in this case, but I feel like reading the source code is probably easier than untangling my rambling explanation, so we have to do better there. Perhaps we should start by figuring out the full `make,grep,grepadd,...` list so we have some practical advice.

That first `cgetfile` is from clearing out the list at the beginning, I forgot about that.
