### ISSUE TITLE
Async mode not async?

### ISSUE THREAD

**Issue by dpo** [tpope/vim-dispatch#257]
I'm using Tmux 2.3 on macOS Mojave (10.14.2) with Terminal (not iTerm2). I configured a `b:dispatch` command to compile LaTeX files. When Vim 8.1.500 is opened inside a Tmux session, issuing `Dispatch!` executes the right command, but is not async; I have to watch the entire compilation until the end... What am I missing?

Thanks!

**Comment by tpope** [comment]
Sounds like #192. Feel free to discuss further there (or just steal a workaround).

**Comment by dpo** [comment]
I'm sorry, I wrote Tmux 2.3, but I'm using Tmux 2.8. Anyways, I'll use the other thread.

**Comment by tpope** [comment]
If that's the case then it's probably not the same issue. But do still try the workaround.

**Comment by tpope** [comment]
Does `:Start` work asynchronously?

**Comment by Fmancino** [comment]
Hi! 
I have a similar problem, Start opens a new tmux window, but 'Make!' is not asyncronous. I am using tmux 2.4  and vim 7.4.

**Comment by dpo** [comment]
Same for me, `Start` opens a new tmux window. Is it supposed to do anything else?
