### ISSUE TITLE
Documentation: Compiler plugins correspondence to dispatch features

### ISSUE THREAD

**Issue by simlei** [tpope/vim-dispatch#259]
Hi,
I looked in the source code and in the documentation for how to achieve the incremental updates in the quickfix list that is showcased for vim-dispatch in the README video. I could not find any directions whatsoever, unfortunately.
I would like to suggest to expand the .txt docs to direct potential developers in the right direction as to such bling. As added bonus, could you already give some pointers here?

Specifically, I did try to start out by generating timed stacktraces with a python script and the [one compiler plugin that works with python](https://github.com/aliev/vim-compiler-python) to see if they would get pulled into the quickfix list as they occurred. They did not, only when the whole process was finished. I am missing clues on

- how to funnel through information like the rails plugin's test progress dots as they appear
- general pointers on interpretation of escape codes, etc etc

**Comment by tpope** [comment]
You can manually update the quickfix with `:Copen`. There is currently no support for automatic updates. It should be possible once #193 is finished, but that's taking longer than expected.
