### ISSUE TITLE
When calling remote_startserver in vimrc, Dispatch falls back to synchronous build

### ISSUE THREAD

**Issue by simlei** [tpope/vim-dispatch#260]
Hi, 
I had dispatch running asynchronously. It used the x11 adapter apparently -- opening an xterm in the background.
After some development I did with VIM8's clientserver feature, whereby I started it with this line in my vimrc:
```
call remote_startserver(string(getpid()))
```
dispatch.vim now executes any Make, Dispatch etc. invocations synchronously.
For me, this does not make any sense -- could it not just use the current `v:servername` if it needs `clientserver`?

Commenting that line gets Dispatch run asynchronously again.

Thanks for ideas!

**Comment by simlei** [comment]
After some debugging, I have concluded that the x11 adapter bails out on these lines:
https://github.com/tpope/vim-dispatch/blob/a795955b64a2eb15c1f05ae1434a89cc8ca16611/autoload/dispatch/x11.vim#L12-L15

If I start the remote server, v:windowid is zero. If I don't, it is not.
I don't like it, I already finished some pretty cool stuff using the clientserver feature :(

**Comment by tpope** [comment]
I can reproduce this but the conditions for it are pretty narrow. If I put the `remote_startserver()` in a `VimEnter` autocommand or use `vim --servername`, v:windowid is nonzero. I'm inclined to write this off as a Vim bug or quirk and leave it to you whether to fix it upstream or just work around it.

**Comment by simlei** [comment]
Thanks for reproducing. I agree that this is a Vim "quirk". The `VimEnter` autocommand strategy is a fine workaround! Can unfork again :)
