### ISSUE TITLE
:Gpush, Iterm 2 "hotkey window" behaviour 

### ISSUE THREAD

**Issue by mvoropaiev** [tpope/vim-dispatch#261]
Hello,
thank you for this plugin (and many others!)
I have encounter an issue while trying vim-dispatch with iterm2.
When working normally, everything seems to be fine, issuing `:Gpush` opens a new tab, switches back to vim tab, process a push and displays a message, but when using "hotkey window" mode in iterm2, issuing `:Gpush` results in new tab being opened, no switch to vim tab happens, and after successful push tab switches to the closest one `git push` was running in (often that's not vim tab, since I have many tabs open usually).
Is this some kind of limitation of "hotkey window" mode or maybe there is something that can be done in order to fix this?

```
iterm2: 3.2.7
vim: 8.1.950
vim-dipatch: 1.7
```

Thanks!

**Comment by mvoropaiev** [comment]
Just in case someone faces the same issue, I've made it work by using alternate approach for making iterm "pop-up" on top of other windows by configuring a key to `Show/hide all windows with a system-wide hotkey` in `Keys` and selecting `All spaces` in `Profile` -> `Window` -> `Space`, this way vim-dispatch is working as expected and also iterm does not get on top of 3rd party apps notifications as well, so double win here :)
Cheers!

**Comment by tpope** [comment]
I don't know the first thing about hotkey window mode, but this sounds like a dispatch.vim issue, so feel free to pipe up there if you have further thoughts!
