### ISSUE TITLE
Dispatch changes working directory of tab

### ISSUE THREAD

**Issue by devth** [tpope/vim-dispatch#262]
I use neovim with tab-local directories (`tcd`). When I start a dispatch in one tab then go to the other, the dispatch window will appear in the 2nd tab and in the process somehow overrides my tab's working dir. Can Dispatch not interfere with other tabs?

**Comment by tpope** [comment]
Sounds like we need something similar to https://github.com/tpope/vim-fugitive/commit/da3b2f32858dda0f15aab79a4c43b3f5c152c0f8 ported over.
