### ISSUE TITLE
Infer makeprg arguments with :Dispatch

### ISSUE THREAD

**Issue by gpanders** [tpope/vim-dispatch#263]
Example: I have a compiler plugin called `pytest.vim` with the following:

```vim
CompilerSet makeprg=pytest\ --tb=short\ -q
CompilerSet errorformat=...
```
When in a Python file, I can type `:Dispatch pytest` (or even better, `` `<Space>pyt<Tab>``) to run the compiler. This properly sets the `errorformat` but does not infer the arguments from the compiler plugin (namely, `--tb=short -q`). This means that to use the pytest compiler, I have to use `:Dispatch pytest --tb=short -q %`. This is a lot to type, and is redundant since I've already specified these arguments in my compiler plugin.

What are your thoughts on inferring the `makeprg` arguments from the compiler plugin if no arguments were provided to `:Dispatch`? So `:Dispatch pytest --foo --bar` would actually run `pytest --foo --bar`, but simply `:Dispatch pytest` would run `pytest --tb=short -q`.

**Comment by tpope** [comment]
I don't think it's documented, but you can invoke a compiler plugin directly with `:Dispatch -compiler=pytest --`. Shortening it to `:Dispatch pytest` would make it impossible to invoke `pytest` without an argument, which is a no go.
