### ISSUE TITLE
How to not auto close quickfix window before calling "Make"

### ISSUE THREAD

**Issue by DasOhmoff** [tpope/vim-dispatch#265]
Hello, thanks for the plugin, its great!

But I have a small question, is there a way to not autoclose the quickfix window when I call the command "Make". What happens to me is that the quickfix window closes when its open and after the command has been executed it reopenes again. Is there a way to prevent the autoclosing?

**Comment by tpope** [comment]
The job adapter, which is now the recommended adapter, leaves the window open.

**Comment by bogdan** [comment]
@tpope can you explain it a little? The doc doesn't mention adapters a lot and I didn't figure out how to get the current adapter I am using.

I don't understand how the quickfix window would not autoclose based on adapter if it is done here:

https://github.com/tpope/vim-dispatch/blob/a2ff28abdb2d89725192db5b8562977d392a4d3f/autoload/dispatch.vim#L1368

It only doesn't autoclose if I change `cwindow` to `copen` on that line.

I am using neovim.

**Comment by tpope** [comment]
@bogdan The original inquiry was about autoclosing immediately after invoking `:Make`, when the command starts running. The code you linked runs when the command *finishes* running. There is no adapter special case for that.
