### ISSUE TITLE
bug: selecting errors in :Dispatch output replaces buffer with a "new file"

### ISSUE THREAD

**Issue by timhemel** [tpope/vim-dispatch#268]
# Setup

Gvim on Fedora core 29:

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar  4 2019 16:21:48)
Included patches: 1-994
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version with GTK3 GUI. 
```
vim-dispatch master branch, revision 178acd05aaf26b14afd0a29f8e1c318ca96637f5
using the pylint compiler on a python file.

# How to reproduce
1. create any python file
2. open it with `gvim`
3. type `:Dispatch pylint %`
4. select any issue in the output window with the enter key, or type `:cnext`.

# Observed behaviour

The buffer that had the open python file is now emptied, the buffer name has the same file, but says `[New File]`.

# Expected behaviour

The buffer should show the opened file at the position that the error indicates.

# Remarks

If I set `:compiler pylint` and then type `:Make %`, everything works as expected.

**Comment by timhemel** [comment]
The 'new file' is called `hello.py:1` instead of `hello.py`. It seems that in `:Make` the error format is communicated to the quickfix window, while in `:Dispatch` it is not.

**Comment by tpope** [comment]
If you focus the quickfix window and `:echo b:current_compiler`, what does it output?

**Comment by timhemel** [comment]
In the quickfix window, I get the following error message:
```
E121: Undefined variable: b:current_compiler
```
If I call `:Dispatch compiler=pylint pylint %`, the variable is also undefined, and in addition the results in the quickfix window are not recognized (no highlighting) and therefore focusing on the compiler error with enter does not work, and neither does `:cnext`. But that may be a different problem (perhaps in this case I did not specify `compiler` correctly).

**Comment by tpope** [comment]
You need `-compiler=pylint`. `compiler=pylint` sets an environment variable.

Looking at the pylint compiler plugin, it adds a bunch of options to `'makeprg'`, such that `:make %` actually calls `pylint --output-format=text --msg-template="{path}:{line}:{column}:{C}: [{symbol}] {msg}" --reports=no %`. Calling `:Dispatch pylint %` doesn't pass those options, so the output is different. You can force it to use the exact pylint `'makeprg'` with `:Dispatch -compiler=pylint -- %`. The `--` is a special argument to `:Dispatch` that causes this behavior.
