### ISSUE TITLE
When wmctrl not available, dispatch is silently headless

### ISSUE THREAD

**Issue by allopislozano** [tpope/vim-dispatch#269]
When wmctrl is not available in the system, Dispatch silently falls back to headless.

I think the behaviour is fine, but I think it would be nice to state it in clearly in the documentation, because in my case it took me a long time to figure out that I needed wmctrl (which my system didn't have) in order  to get an xterm to pop up and actually show the compilation.

Great plugin! Kudos

**Comment by tpope** [comment]
[It's mentioned](https://github.com/tpope/vim-dispatch/blob/929e0d0aa1139d483c070e4ee2a05f4a3425b0af/doc/dispatch.txt#L198-L200). "Clearly" is subjective I guess.
