### ISSUE TITLE
Redrawing issues when launching xterm over vim window 

### ISSUE THREAD

**Issue by allopislozano** [tpope/vim-dispatch#274]
Using vim 8, latest version of vim Dispatch. Great tool !

I usually get visual artifacts in vim when I launch the compiler with :Dispatch or :Make . For example the area of vim below xterm usually goes blank. Sometimes scrolling helps, but usually I need to manually :redraw! 

Thanks a lot!

**Comment by tpope** [comment]
I was thinking of removing `:Dispatch` support for xterm, actually, now that we have job support. Is there a reason you're not using the job adapter?

**Comment by allopislozano** [comment]
I didn't know about the job adapter :P

**Comment by tpope** [comment]
If you're on the very latest version, it should work out of the box with `:Make` and `:Dispatch`. In fact, it should be basically impossible to call the old xterm support unless you override the default priorities. Did you change `g:dispatch_handlers`?

**Comment by allopislozano** [comment]
Looks like I had not updated yet to the latest version. Thanks a bunch and I love your vim tools =)
