### ISSUE TITLE
The handle is invalid - Windows 10

### ISSUE THREAD

**Issue by run2cmd** [tpope/vim-dispatch#275]
I have problem with Invalid Handle message when using Windows 10 with WSL. 

I have blow dispatch setup for rspec thests I run on WSL
```
autocmd Filetype ruby let b:dispatch = "bash.exe --login -c \"echo '%' \| tr -s '\\' '/' \| xargs -i rspec {}\""
autocmd Filetype yaml,yml let b:dispatch = "bash.exe --login -c \"ansible-lint '%'\""
```

This was working with commit 9096c8bba04046a18d252bb21dabec3bb3fedbbe, but does not work with latest vim-dispatch

I need to run in WSL since I have Augeas code which I'm not able to test under Windows. No Augeas libraries for Windows.

**Comment by tpope** [comment]
Are you running the usual Windows GVim, or a WSL version?

Does it work with commands that don't do the nested quotes thing?

**Comment by run2cmd** [comment]
I'm using usual Windows GVim. 

:chistory shows:
```
> error 1 of 1; 26 errors     :Dispatch bash.exe --login -c "echo 'spec/defines/augeas_config_change_spec.rb' | tr -s '\' '/' | xargs -i rspec {}" (job/19396)
```
I have tried to run with just `:Disptach bash.exe` and in both cases I get the same output

command output
```
|| T
|| h
|| e
||  
|| h
|| a
|| n
|| d
|| l
|| e
||  
|| i
|| s
||  
|| i
|| n
|| v
|| a
|| l
|| i
|| d
|| .
|| 
|| 
|| 
|| 
```

Also when I run extenral command the same as in :chistory then it works properly.
```
:!bash.exe --login -c "echo 'spec/defines/augeas_config_change_spec.rb' | tr -s '\' '/' | xargs -i rspec {}"
```
command output
```
C:\WINDOWS\system32\cmd.exe /c (bash.exe --login -c ^"echo 'spec/defines/augeas_config_change_spec.rb' ^| tr -s '\' '/' ^| xargs -i rspec {}^")
RVM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
you can ignore these warnings with 'rvm rvmrc warning ignore /mnt/d/code/puppet/jboss/Gemfile'.
To ignore the warning for all files run 'rvm rvmrc warning ignore allGemfiles'.

tr: warning: an unescaped backslash at end of string is not portable

jboss::augeas_config_change
  no jboss class defined
    should fail to compile and raise an error matching /Must define jboss base class before use/
  eap6
    should compile into a catalogue without dependency cycles
    should contain Augeas[test change] that requires File[/etc/jbossas/testinstance/standalone-full-ha.xml]
  eap7
    should compile into a catalogue without dependency cycles
    should contain Augeas[test change] that requires File[/etc/opt/rh/eap7/wildfly/testinstance7/standalone-full-ha.xml]

Finished in 13.18 seconds (files took 4 seconds to load)
5 examples, 0 failures

Coverage report generated for RSpec to /mnt/d/code/puppet/jboss/coverage. 0.0 / 0.0 LOC (100.0%) covered.
Hit any key to close this window...
```

**Comment by tpope** [comment]
Try these three:

```viml
:Dispatch echo test
:Dispatch bash -c 'echo test'
:Dispatch bash --login -c 'echo test'
```

**Comment by run2cmd** [comment]
1st one succeded and returned test message
2nd and 3rd one failed with "The handle is invalid message"

chistory shows:
```
error list 1 of 2; 1 errors      :Dispatch echo test (job/14220)
error list 2 of 2; 26 errors    :Disptach bash -c 'echo test' (job/18656)
```

**Comment by tpope** [comment]
I don't have much else to suggest other than trying to running job directly:

    :let g:jobbuf = []|let g:job = job_start([&shell, &shellcmdflag, "bash -lc 'echo test'"], {'mode': 'raw', 'callback': {j, o -> add(g:jobbuf, o)}})
    :echo g:jobbuf

If you can get this or some variant of it to work, I can probably fix it in dispatch.vim. Until then I'm out of ideas.

Can any other WSL uses chime in with whether `:Dispatch bash -c 'echo test'` works?

**Comment by tpope** [comment]
P.S. You can work around this issue by doing `let g:dispatch_no_job_make = 1` and the Windows strategy will handle it instead. (But that's an inferior experience and I'd like to remove it at some point.)

**Comment by run2cmd** [comment]
Both `let g:dispatch_no_job_make = 1` and running directly worked. I'll use the `let g:dispatch_no_job_make = 1` for now until I find nice way to utilize direct running.

Thanks for help :)

**Comment by tpope** [comment]
If that `job_start` worked we can probably fix it. Can you try the `win32` branch?

**Comment by run2cmd** [comment]
Looks like it works. I was able to run `:Dispatch bash.exe --login -c 'echo test'` and got proper output.
However when I tried to run with `%` as a current file name it did not work as expected.

Command: `:Dispatch bash.exe --login -c 'echo spec\defines\augeas_config_change_spec.rb'`
Output: `"specdefinesaugeas_config_change_spec.rb"`

Command: `:Dispatch bash.exe --login -c 'echo -E "spec\defines\augeas_config_change_spec.rb"'`
Output: `"specdefinesaugeas_config_change_spec.rb"`

Command: `:!bash.exe --login -c 'echo -E "spec\defines\augeas_config_change_spec.rb"'`
Output: `spec\defines\augeas_config_change_spec.rb`

Command: `:let g:jobbuf = []|let g:job = job_start([&shell, &shellcmdflag, "bash -lc 'echo -E \"spec\defines\augeas_config_change_spec.rb\"'"], {'mode': 'raw', 'callback': {j, o -> add(g:jobbuf, o)}})`
Output: `"specdefinesaugeas_config_change_spec.rb"`

Commands: `:let g:jobbuf = []|let g:job = job_start([&shell, &shellcmdflag, 'bash -lc "echo test"'], {'mode': 'raw', 'callback': {j, o -> add(g:jobbuf, o)}})`
Output: `'test": -c: line 0: unexpected EOF while looking for matching `"''`

Command: `:let g:jobbuf = []|let g:job = job_start([&shell, &shellcmdflag, "bash -lc 'echo test'"], {'mode': 'raw', 'callback': {j, o -> add(g:jobbuf, o)}})`
Output: `test`

Seems `\` is treated as escape sign regardless of quoting. I got only below working properly:
Commnad: `:let g:jobbuf = []|let g:job = job_start([&shell, &shellcmdflag, substitute("bash -lc 'echo -E spec\\defines\\augeas_config_change_spec.rb'", '\', '/', 'g')], {'mode': 'raw', 'callback': {j, o -> add(g:jobbuf, o)}})`
Output: `spec/defines/augeas_config_change_spec.rb`

But I do not know how to inject that into vim-dispatch. If that is even possible.

**Comment by run2cmd** [comment]
I have solved it. I took a different approach and put more work for VIM itself

```
autocmd BufWinEnter * let b:unix_path = substitute(expand('%'), '\', '/', 'g')
autocmd BufWinEnter *_spec.rb let b:dispatch = "bash.exe --login -c 'rspec " . b:unix_path . "'"
```

I had to do it in `BufWinEnter` since I'm using also plugin called vim-rooter that changes CWD to GIT/SVN project root. But for people that do not use it `FileType` should be enough

**Comment by tpope** [comment]
Yeah if you're mixing shells, you're definitely gonna have to take responsibility for some escaping. Something like this might work:

    autocmd BufReadPost *_spec.rb let b:dispatch = "bash.exe --login -c 'rspec %:gs?\\\\?/?'"

(You need 4 backslashes to account for both the `""` string escaping and the `??` regexp escaping.)

**Comment by tpope** [comment]
Also, try `:set shellpath` to use forward slashes everywhere. (This might have other undesirable side effects.)
