### ISSUE TITLE
Very slow to open when running inside tmux with shell=fish

### ISSUE THREAD

**Issue by anark** [tpope/vim-dispatch#276]
When running ```:Dispatch rspec %``` from within a tmux session with ```set shell=/usr/local/bin/fish``` it takes over 8 seconds to open the new tmux pane and start running the command.

With ```set shell=sh``` the pane opens immediately and starts running.

Any idea how to improve this when using fish shell?

**Comment by tpope** [comment]
I guess start by calling `/usr/bin/fish -c 'rspec somefile'` and see how slow it is.

**Comment by anark** [comment]
Calling ```/usr/local/bin/fish -c 'rspec some_spec.rb'``` works fine both in and out of tmux.

The delay is before the tmux pane is opened.  Once the pane is opened the spec runs as expected.

**Comment by anark** [comment]
Running
``` 
:profile start profile.log
:profile func *
:profile file *
:Dispatch echo 'HELLO'
:profile pause
```

Gives the following summary
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    1   8.110366   0.000840  dispatch#compile_command()
    1   8.031667   0.016956  <SNR>97_dispatch()
    1   7.452974   0.000171  dispatch#tmux#handle()
    1   5.343489   0.000000  dispatch#tmux#make()
    1   1.087409   0.001452  dispatch#isolate()
    1   1.086595   0.000111  <SNR>98_pane_id()
    1   1.062489   0.000043  dispatch#prepare_make()
    1   1.062370   0.000119  dispatch#prepare_start()
    1   1.062236   0.001287  dispatch#callback()
    4   1.050524   0.000199  dispatch#has_callback()
    4   0.561548   0.000053  <SNR>97_postfix()
    4   0.561496   0.561478  dispatch#pid()
    1   0.084020   0.031217  dispatch#complete()
    1   0.076976             <SNR>97_compiler_split()
    1   0.052568   0.000452  <SNR>97_cwindow()
    3   0.042900   0.000100  coc#rpc#request()
    3   0.042771   0.042606  <SNR>34_request()
    1   0.024423   0.001426  rails#buffer_setup()
    5   0.013440   0.000427  lightline#update()
    1   0.013304   0.000501  <SNR>75_BufProjectionCommands()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    4   0.561496   0.561478  dispatch#pid()
    1              0.076976  <SNR>97_compiler_split()
    3   0.042771   0.042606  <SNR>34_request()
    1   0.084020   0.031217  dispatch#complete()
    1   8.031667   0.016956  <SNR>97_dispatch()
   21              0.007113  lightline#link()
   10   0.012739   0.004913  <SNR>69_line()
   86   0.004672   0.004520  <SNR>75_extend_projection()
   20   0.006360   0.004299  <SNR>69_expand()
   12   0.007906   0.003234  <SNR>75_combine_projections()
    1   0.008872   0.002525  <SNR>75_app_commands()
    1   0.003049   0.002459  <SNR>9_LoadFTPlugin()
   17   0.002211   0.002091  <SNR>75_define_navcommand()
    1   0.002455   0.001841  AutoPairsInit()
    1   0.006407   0.001738  <SNR>75_readable_projected_with_raw()
   21   0.001745   0.001604  <SNR>34_notify()
   70              0.001559  <SNR>69_convert()
   30              0.001466  <SNR>69_subseparator()
    1   1.087409   0.001452  dispatch#isolate()
    1   0.024423   0.001426  rails#buffer_setup()
```

**Comment by tpope** [comment]
That makes me think that every `system('tmux')` call (like [this one](https://github.com/teoljungberg/vim-dispatch/blob/3f98dc37eb60becb99a85166a919079fc4e9dd6d/autoload/dispatch/tmux.vim#L16)) is adding a second or two of overhead.

**Comment by anark** [comment]
Ahh, I see.  I have added ```set shell=/bin/sh``` and dispatch now works correctly as fish did not work properly with the system calls.  This was being overridden by the vim-opinion plugin which was setting shell back to fish.

Ideally I would be able to run fish as the shell in the neovim :terminal and use sh for all plugins but for now using a shell of sh for vim works more reliably then having fish as the shell.

Thanks for you help diagnosing this.

**Comment by tpope** [comment]
There's nothing to change them to. I don't think `fish` *has* to be slow, you should investigate why it is!
