### ISSUE TITLE
Feature: Ability to cancel / abort a dispatched command

### ISSUE THREAD

**Issue by dhruvasagar** [tpope/vim-dispatch#28]
Not sure how many would find this useful, but I would like to be able to abort a dispatched task and most importantly ignore it's output and not have it loaded into quickfix list.

Perhaps I should :Start such a command rather than :Dispatch, but in either case currently there's no support for being able to abort it from within vim and as of now I am not even sure if it is feasible, so just putting it out there, and I can see this to be useful in both cases with :Start and :Dispatch.

**Comment by bounceme** [comment]
Something like this would be helpful in stopping long running processes that are started headless.

**Comment by tpope** [comment]
Went with a simple string match for aborting older tasks. I could see adding something similar to `:Copen`, to help with @shym style scenarios. This doesn't preclude adding other specification methods, though I think the `@^` style stuff is probably overkill.
