### ISSUE TITLE
Dispatch opens tmux pane and job

### ISSUE THREAD

**Issue by thrgamon** [tpope/vim-dispatch#287]
Hi,

I am running nvim `0.4.3` with dispatch `v1.8` inside tmux `3.0a` and I have just started seeing a weird behaviour. 

When I call `:Dispatch bin/rspec %` for example, it will run the test both in a tmux split AND ~inside the neovim terminal~ as a job simultaneously. I have previously used dispatch with no trouble and it faithfully just would open a tmux split.

I have recently updated to Mac OS Catolina, which may or may not be related. 

Is there anything I can look into to try and troubleshoot this?

Many thanks!

Tom

**Comment by tpope** [comment]
Dispatch does not yet have native Neovim terminal support. Are you using a plugin for that?

**Comment by thrgamon** [comment]
Ah woops, sorry, I just assumed that was what was going on. Looking a bit closer, it looks like it is in fact running a job.

**Comment by thrgamon** [comment]
Hmm, I am not sure if this was the root cause of the issue, but fixing an issue in my tmux config from upgrading to tmux `3.0` seems to resolved the problem 🤷‍♂ 

Either way, thanks for your time on this as well as the time you spend on all your plugins!
