### ISSUE TITLE
Accessing/clearing tmp file

### ISSUE THREAD

**Issue by maxigit** [tpope/vim-dispatch#288]
I'm using vim-dispatch with ghcid (which is an haskell tool retriggering compilation/test each time a file is modified). Everything works great however, even though the compilation is restarted, the errors accumulate (from the previous run). I would like to be able to clear the temporary file used by vim-dispatched, so that I only get the errors from now (restarting ghcid is not an option has it a slow startup). I'm happy to erase the file manually but I don't even know where is it  on the filesystem.
Can anyone help ?

**Comment by tpope** [comment]
You can find the filename of the most recent dispatch in the Vim option `'errorfile'`. It's mainly intended for debugging, caveat emptor.

**Comment by maxigit** [comment]
Thanks :-)
