### ISSUE TITLE
Send keys to underlying tmux pane

### ISSUE THREAD

**Issue by maxigit** [tpope/vim-dispatch#289]
Hi, I'm using vim-dispatch to launch an interactive repl (haskell via ghci).
At the moment i'm using the vim-tbone plugin to send command (I'm not really bothered yet about getting information back, as I can read the error buffer using `errorfile`). Everything works fine but to do be able to use `tbone#send_key` I need to guess the tmux pane created by vim-dispatch.
Is there an easy way in vim-dispatch to get the tmux pane or even a function to send command to it ?

**Comment by tpope** [comment]
This isn't exposed. I imagine grabbing the most recently opened pane from tmux immediately after `:Dispatch` would be pretty straightforward.

**Comment by maxigit** [comment]
At the moment I use '+' which means the next pane. It  works until I mess around with the pane and move it to another window or even another session. 
I could indeed make a wrapper around `:Dispatch` (and all other commands) but it might be easier to expose a function return the tmux pane if it exists already

**Comment by maxigit** [comment]
I realized I can just use a global variable and modify it manually if  I need to, so exposing a function a function is not really necessary. Thank you for you prompt answer.
