### ISSUE TITLE
Grepping asynchronously with vim-dispatch

### ISSUE THREAD

**Issue by hariamoor** [tpope/vim-dispatch#290]
I was wondering about a strategy to `:grep` asynchronously with this plugin. It's a natural use-case, since `:grep` requires the QuickFix window, but there's no natural way to do this, as far as I've read from the helpfile.

If this doesn't exist, would you consider supporting a simple `:Grep` command that asynchronously launches `:grep` and respects `grepprg` and `grepformat`?

**Comment by tpope** [comment]
`:make` and `:grep` are close cousins; it's a very natural fit. The reason I decided against providing it was that `grep` is generally quite fast compared to the overhead of creating a tmux window, etc, and thus generally an inferior experience unless you're searching a *huge* project. The new job adapter lowers the overhead and makes it a lot more viable, but that raises the awkward question of whether `:Grep` should have a higher priority for the job adapter than the tmux adapter.

I'm also hesitant to add a `:Grep` command to a 7 year old plugin; I can't imagine that won't conflict with other implementations. I'm inclined to instead recommend you one of the following in your own config, perhaps packaging up your own plugin:

* Make a `compiler/grep.vim` that sets `'makeprg'` and `'errorformat'` to the default values of `'grepprg'` and `'grepformat'`. Then you can `:Dispatch grep` to get the desired effect. (You could also make a `compiler/ag.vim`, etc.)
* Make a `:Grep` command that temporarily sets `'makeprg'` and `'errorformat'` to `'grepprg'` and `'grepformat'`, calls `:Make`, and restores their values afterwards.
* Make your own fully independent `:Grep` built on jobs, perhaps by cannibalizing `autoload/dispatch/job.vim`. Somebody has probably already done this, actually.

I will revisit this if I ever decide to ditch the alternative handlers like tmux, but until then I think it's a can of worms I don't want to open.
