### ISSUE TITLE
Working with MiniTest and RSpec?

### ISSUE THREAD

**Issue by nomasprime** [tpope/vim-dispatch#291]
Raised an issue over [here](https://github.com/janko/vim-test/issues/423) because that's the wrapper I'm using for Neomake and Dispatch.

Have a feeling the problem lies with Dispatch though because when I use directly the error messages still don't get picked up.

**Comment by nomasprime** [comment]
🎉 [this](https://github.com/tpope/vim-dispatch/issues/198) fixed part of the issue.

**Comment by nomasprime** [comment]
Last problem I'm having is with output: `^[[1A^[[2K^MStarting euclid_neo4j_1 ... ^[[32mdone^[[0m^M^[[1B/usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/stack.rb`

There's also a problem with the inline output in Neomake so hopefully if I can fix in Dispatch, it will fix that too.

**Comment by tpope** [comment]
If the issue is happening with tmux, `:set shellpipe=2>&1\|tee` might fix it, because that tells Dispatch to use that pipe construction to capture output rather than use `tmux pipe-pane`. If it's happening with any other adapter, then it's the fault of the command you're running. It shouldn't try to write escape codes to something that isn't a tty.

**Comment by nomasprime** [comment]
Thanks @tpope.

I've already tried that and some of the other `shellpipe` settings I found in the issues but couldn't get it to work.

If I run directly with Dispatch I see some of the same escape codes, could be a problem with the way I'm running Dip/Docker? I'll look into that.

Also raised an issue with Neomake see if they can help.

**Comment by nomasprime** [comment]
Tried running directly with Docker, without Dip, with both interactive and non-interactive. I get the same result.

**Comment by tpope** [comment]
I don't know what any of that means.

**Comment by nomasprime** [comment]
Essentially I get the same output with/without Docker.

The problem's most visible when Neomake displays errors so hoping they can get to the bottom of it.

In the meantime I'll educate myself around shells, escape codes, etc. Any recommended resources?

**Comment by nomasprime** [comment]
Got working in Docker but now trying locally to compare performance.

Unfortunately with pretty standard install it's not working again with MiniTest and RSpec. I'm calling Dispatch directly.

**Comment by nomasprime** [comment]
Tried setting compiler to `ruby` and `rubyunit`.

Tried with both `ruby -Itest %` and `ruby -I test %`.

Test results come up with errors but nothing's matched.

**Comment by nomasprime** [comment]
Maybe not compatible with NeoVim?

**Comment by nomasprime** [comment]
Tried in unmodified Vim, even jumping into unmodified Bash shell, and the same. Just trying to eliminate things best I can.

**Comment by tpope** [comment]
You can use `:Dispatch -compiler=rubyunit` to force a particular Vim compiler plugin. Make sure you're not using a custom Minitest formatter, as that could potentially format the errors in a away the compiler plugin won't recognize.

**Comment by nomasprime** [comment]
@tpope thanks. I'm not using any custom formatter, deliberately gone vanilla.

Aren't there some bugs here?

Even if I force the compiler I don't get any joy with Minitest.

Rspec I can get to work if I don't use `bundle exec`.

**Comment by tpope** [comment]
It's been years since I've had the occasion to use Minitest. It's plausible the default output format changed to the point the `rubyunit` compiler plugin can no longer recognize it.

**Comment by nomasprime** [comment]
@tpope can we reopen this issue? Still not working for me but I'll have a go at fixing it.

**Comment by nomasprime** [comment]
@tpope is this a Dispatch bug? How can I fix this?

**Comment by tpope** [comment]
Highly unlikely that this is a Dispatch bug. Try `:compiler ruby` and `:make %` to see if you get the same result with Dispatch removed from the equation.
