### ISSUE TITLE
Can I see full raw command output from :Dispatch?

### ISSUE THREAD

**Issue by dbarnett** [tpope/vim-dispatch#293]
I can't find any way to view the full output (stdout and stderr) from a command, only the quickfix entries. Is there a way?

**Comment by tpope** [comment]
`:Copen!`

**Comment by duckdalbe** [comment]
I was looking for this piece of information for hours! Thank you!

Is it documented somewhere? If not, I suggest to maybe do that. `dispatch` is full of wonderful possibilities, some of which are not easy to find.

**Comment by tpope** [comment]
https://github.com/tpope/vim-dispatch/blob/1206e1474fc613caeb1ba56d36b71d7f9f7760ac/doc/dispatch.txt#L32-L34
