### ISSUE TITLE
binding.pry does not work when running specs

### ISSUE THREAD

**Issue by ioanniswd** [tpope/vim-dispatch#294]
Having added a `binding.pry` in the code to test and using vim-test, the pry console does not appear in the window. When running `:Dispatch ./bin/rspec %` directly, it does pause for a few seconds where `binding.pry` was placed, but modifiable is off and I cannot do anything. Not sure if there is a solution to this.

**Comment by tpope** [comment]
The solution is to use `:Spawn` instead of `:Dispatch`. If you have a default `b:dispatch` configured, `:0Spawn` will use it automatically. I don't know if vim-test provides a mechanism for this.
