### ISSUE TITLE
:Start -wait doesn't work as intended

### ISSUE THREAD

**Issue by geratheon** [tpope/vim-dispatch#296]
Hi!

If starting a process with `:Start -wait="error"` it always says `Press ENTER or type command to continue`, but it should suppress the prompt on return code 0, as it's stated in the docs.

You can reproduce this with `:Start -wait="error" false` and `:Start -wait="error" true`. Right now, both prompt for the return key. The same applies to `-wait="never"`.

Because I wasn't sure what's right I also tested it without the quotation marks (`-wait=error`), but that doesn't work either.

I'm using Vim 8.2.460 and the current master (fe6a34322829e466a7e8ce710a6ac5eabddff9fd) of vim-dispatch.

Thanks!

**Comment by tpope** [comment]
The quotes do *not* work. Did you test with `-wait=never`?

What adapter are you using?

**Comment by geratheon** [comment]
> The quotes do not work.

Good to know, it is not stated exactly in the documentation, it could've been both. But yeah, I tested both, `:Start -wait=never false` also prompts for the return key. 🤔

> What adapter are you using?

With adapters you mean the `:h dispatch-strategies`, right? I'm working exclusively via ssh on a linux and without tmux or screen right now, so I probably use the `Synchronous` one. Sorry, I forgot to state this in the original report!

**Comment by tpope** [comment]
The synchronous strategy is a bare bones fallback built on `:!`. indeed it does not support `-wait`. It would be possible to support `-wait=never` with `silent` and `redraw!`. Supporting `-wait=error` gets tricky. Personally, I will channel what time and energy I have into #250, as it will solve this by rendering the synchronous adapter largely obsolete.
