### ISSUE TITLE
Incorrect Quickfix formatting for Python using Dispatch + Pylint

### ISSUE THREAD

**Issue by dc1800** [tpope/vim-dispatch#299]
Running `:Dispatch` or `:Dispatch pylint %` in a python file brings up the quickfix window (or is it the location window?), but the lines come out a little mangled:
```
Expected:
|| ************* Module project
project.py|136 C| [line-too-long] Line too long (125/100)
project.py|139 col 2 warning| [fixme] TODO not converting directly to datetime
project.py|150 col 2 warning| [fixme] TODO refactor this...
project.py|28 warning| [pointless-string-statement] String statement has no effect
project.py|171 col 61 error| [undefined-variable] Undefined variable 'tasks'
|| 
|| ------------------------------------------------------------------
|| Your code has been rated at 7.75/10 (previous run: 7.75/10, +0.00)
|| 

Actual:
|| ************* Module project
project.py:136|| C0301: Line too long (125/100) (line-too-long)
project.py:139|2| W0511: TODO not converting directly to datetime (fixme)
project.py:150|2| W0511: TODO refactor this... (fixme)
project.py:28|| W0105: String statement has no effect (pointless-string-statement)
project.py:171|61| E0602: Undefined variable 'tasks' (undefined-variable)
|| 
|| ------------------------------------------------------------------
|| Your code has been rated at 7.75/10 (previous run: 7.75/10, +0.00)
|| 
```
Which of course means that running `:cn` or pressing enter in the quickfix window opens new files named `project.py:136`, `project.py:139`, etc. The quickfix window comes up formatted perfectly if I run:
```vimscript
:compiler pylint
:Make %
````
so it seems to be something in `:Dispatch`. I tried the `:set shellpipe+=\` solution mentioned in some of the other issues (didn't help in my case) and emptied out my .vimrc thinking some other setting caused the problem, but the behavior has persisted, whether in tmux, plain gnome-terminal, or Gvim.

I can work around it by mapping \`\<CR> to `:Make %<CR>`, but is there some setting in Vim or Dispatch that I've overlooked? Thanks for all your awesome plugins!

**Comment by tpope** [comment]
Check `:echo b:current_compiler` while the quickfix window is focused. This will be the compiler plugin that was used to generate that quickfix list.

**Comment by dc1800** [comment]
Hmm... quickfix window returns `pylint` in all cases:
### `` `<CR> `` (aka `:Dispatch`): 
`:echo b:current_compiler` --> `pylint`
Quickfix format: :x:
```
|| ************* Module project
project.py:31|| C0301: Line too long (105/100) (line-too-long)
project.py:52|1| W0511: TODO pass in a file and parse it (fixme)
project.py:53|4| E1120: No value for argument 'priority' in method call (no-value-for-parameter)
[... additional lines omitted for brevity ...]
|| 
|| ----------------------------------------------------------------------
|| Your code has been rated at -14.67/10 (previous run: -14.67/10, +0.00)
|| 
```

### `:Make %` (command from Dispatch): 
`:echo b:current_compiler` --> `pylint`
Quickfix format:  :heavy_check_mark:
```
|| ************* Module project
project.py|31 C| [line-too-long] Line too long (105/100)
project.py|52 col 1 warning| [fixme] TODO pass in a file and parse it
project.py|53 col 4 error| [no-value-for-parameter] No value for argument 'priority' in method call
[... additional lines omitted for brevity ...]
|| 
|| ----------------------------------------------------------------------
|| Your code has been rated at -14.67/10 (previous run: -14.67/10, +0.00)
|| 
```

### `:make %` (standard vim command, to show raw pylint output):
`:echo b:current_compiler` --> `pylint`
Initial output:
```
[No write since last change]
************* Module project
project.py:31:0:C: [line-too-long] Line too long (105/100)
project.py:52:1:W: [fixme] TODO pass in a file and parse it
project.py:53:4:E: [no-value-for-parameter] No value for argument 'priority' in method call
[... additional lines omitted for brevity ...]

----------------------------------------------------------------------
Your code has been rated at -14.67/10 (previous run: -14.67/10, +0.00)


Press ENTER or type command to continue
```
and then `:copen`: :heavy_check_mark: (Identical to `:Make %` above.)
```
project.py|31 C| [line-too-long] Line too long (105/100)
project.py|52 col 1 warning| [fixme] TODO pass in a file and parse it
project.py|53 col 4 error| [no-value-for-parameter] No value for argument 'priority' in method call
[... additional lines omitted for brevity ...]
```

**Comment by cloose** [comment]
Maybe related to #225?

**Comment by tpope** [comment]
Good catch, my comment there would be my recommended solution.

**Comment by dc1800** [comment]
Just applied the suggested fix (namely, I added `autocmd FileType python let b:dispatch = 'pylint -f parseable %'` to my vimrc) and indeed it now works like a champ. Thanks @cloose and @tpope !
