### ISSUE TITLE
Asking for password for sudo make install ?

### ISSUE THREAD

**Issue by hugo-manet** [tpope/vim-dispatch#300]
Hi !
My `makeprg` contains a `sudo make install` ; but this needs a prompt for a password. How can I make this work ? My `:Make` opens in a new split (the quickfix windows I guess), and sudo complains it doesn't have a TTY...
(Google solutions all say to configure sudo not to ask the password for that command, but obviously I don't want anyone to be able to just sudo make whatever they want ^^ )

**Comment by tpope** [comment]
I recommend `sudo -A`.
