### ISSUE TITLE
New mapping m% and m*

### ISSUE THREAD

**Issue by maxigit** [tpope/vim-dispatch#303]
`vim-dispatch` uses some clever mapping starting with `m` having noted that some marks can't be set and therefore can not work in conjunction with `m` (like `m<space>` `m!` etc ...). Following the same philosophy I propose to add two mappings

    - `m%` call `:Make` on the current file. Equivalent to `:Make %<CR>` but should actually expand `%` to the filename so that the command name in `request` are different if called on different files
    - `m*` call `:Make` on the target under cursor. Handy to execute the target undercusor in a makefile for example

I'm happy to provide PR if needed.

**Comment by tpope** [comment]
These are both cans of worms I don't think I want to open. `:Make %` does not fit the classic `make` usage. You're never building the current file, you're building a derivative, like `%:r.o` for example. And for `:Make *` "target under cursor" is doing a lot of heavy lifting: in a `Makefile`, this is "closest unindented line, scanning upwards, matching up to the first colon." Even if you simplify to "identifier under cursor", for a `Makefile` this would need to be a definition of identifier that includes period but excludes colon.

Both of these use cases can be better addressed, in my opinion, with a default dispatch.  For the cursor task, you'll need to use a linewise default on `:.Dispatch`, which is undocumented but see https://github.com/tpope/vim-bundler/commit/25af18c78adec538b019584e30f45a17e02a3c2e for an example.
