### ISSUE TITLE
"Press ENTER to continue" should accept only ENTER and not every key

### ISSUE THREAD

**Issue by guestname** [tpope/vim-dispatch#304]
If I run ":Start", after the command finishes the promp appears "Press ENTER to continue". However, if I press any key, it continues anyway, and this is a bit annoying (I have some shortcuts from other programs, and if I use them I have to run :Start again).

Also the "-wait=never" option doesn't seem to work.

**Comment by tpope** [comment]
What strategy is in use?

**Comment by guestname** [comment]
> What strategy is in use?

Job.

**Comment by tpope** [comment]
The job strategy is a `:Make` (and `:Dispatch`) strategy only, not `:Start`. Sounds like you are defaulting to the synchronous handler, backed by `:!`. And `:!` behaves like you describe, this is basically set in stone.

I don't understand "I have some shortcuts from other programs".

**Comment by guestname** [comment]
> And `:!` behaves like you describe, this is basically set in stone.

Ha, that explains why everything I tried by editing the plugin's source code didn't work.

Thanks, anyway.
