### ISSUE TITLE
Is there an API for feeding stdin?

### ISSUE THREAD

**Issue by unphased** [tpope/vim-dispatch#307]
I hope you're familiar with coc-nvim. I use this and I have started to create custom "vim/tmux IDE" capabilities after a similar fashion. I've got a server process which I currently use https://github.com/prabirshrestha/async.vim to spawn as a vim/nvim job. That plugin is a very simple wrapper around the jobs features built into vim/nvim. 

Then, what this system does is it hosts a simple node.js server (currently using a unix domain socket for now but it'd be easy to upgrade that to a full blown network socket), and I push onto this process's stdin messages specific to interactions I care about that I perform in Vim. e.g.: 

    au FocusGained * if !exists('s:vimHelperServerJobDead') | call async#job#send(s:vimHelperServerJob, "FocusGained:".expand('%:p')."\n") | endif

So that gives you an idea of how this works. Then, the frontend of this IDE would be another pty running another node process which opens net clients to the server and performs actions based on these messages. 

For completion's sake here's the vimL code that spawns the server: 

    let s:vimHelperServerJob = async#job#start(["bash", "-c", '(cd ~/util; ./node_modules/.bin/nodemon --watch vimhelper_server.ts --exec "ts-node vimhelper_server.ts '.getpid().'")'], {'on_exit': function('s:async_job_handler'), 'on_stderr': function('s:async_job_stderr_handler'), 'on_stdout': function('s:async_job_stdout_handler')})

Right. This would be insane gibberish unless you are aware of typescript development patterns (I don't recommend it). Anyway, my question boils down to this: 

I have a "sidecar" server I spawn alongside my vims. I am using https://github.com/prabirshrestha/async.vim to spawn them, and although it works great, it leaves much to be desired because there is nothing in place to have the output displayed beautifully in a buffer or window when input comes in from it. I'm having trouble finding dispatching plugins (https://github.com/skywind3000/asyncrun.vim is another) that are built for anything more fundamentally flexible than running builds and what amounts to assembling quickfix buffers out of error messages (which believe me I dig, just not actually something that I've found I want to use yet). In particular, I'm looking for a more featured plugin **such as this one** that can handle the arbitrary process spawning bit, which also provides some kind of API for asynchronous stdin access.

**Comment by unphased** [comment]
I'm feeling like the way for me to go is to manually manage a scratch buffer and use something like https://github.com/powerman/vim-plugin-AnsiEsc for getting colors working. Because it seems like async stdin injection is too tall of an order even for the terminal feature in vim (for example)

**Comment by tpope** [comment]
I don't think this is a good fit? We could certainly add an API for feeding stdin, at least with the job adapter, but that won't solve the problem that it's still fundamentally for capturing the output of a short running command and populating it into the quickfix list.
