### ISSUE TITLE
:lmake support

### ISSUE THREAD

**Issue by JazzCore** [tpope/vim-dispatch#31]
Is it possible to add async version of a `:lmake`? I'm looking for an opportunities of making [Syntastic](https://github.com/scrooloose/syntastic) asynchronous. Since it uses a `:lmake` for running syntax checkers and heavily bound to location list, sadly simple switch to `:Make` doesnt work. I guess i can hack into this, but my vimscript-foo does not stand a change against yours :)

**Comment by Konfekt** [comment]
In the meanwhile, give [tasks](https://github.com/mg979/tasks.vim/blob/master/docs/1-async.md#make-commands) a whirl.
