### ISSUE TITLE
failed Dispatch job overwrites buffer

### ISSUE THREAD

**Issue by ranjithshegde** [tpope/vim-dispatch#312]
###:Expected behavior
When dispatch job fails, it should write to quickfix list the same way :Make errors are written to quickfix lists

###:Actual behavior
it overwrites the current buffer. No way to switch back to the contents of the buffer without exiting vim (I just made the mistake of habitually exiting vim with :x and lost the file

![overwrite](https://user-images.githubusercontent.com/10258296/117722562-80b47480-b1e1-11eb-9434-90f0706bf821.gif)

**Comment by tpope** [comment]
See if you can reproduce with a minimal config. This smells like some other autocommand misbehaving.

**Comment by ranjithshegde** [comment]
found the problem in one of autocmds related to netrw! Thanks for pointing me in the right direction
