### ISSUE TITLE
passing environment variable to the dispatched command

### ISSUE THREAD

**Issue by nimaai** [tpope/vim-dispatch#316]
Hi 

I need to pass an environment variable like: `FOO=bar rspec ...`

How do I do that?

Thanks

**Comment by tpope** [comment]
You can do it the way you would for any `:!` command, but that will generally break compiler auto-detection. So you will need, for example, `:Dispatch -compiler=rspec FOO=bar rspec`. If it's always the same variable, with the same value, you can fix the auto-detection by adding a special case:

```vim
if !exists('g:dispatch_compilers')
  let g:dispatch_compilers = {}
endif
let g:dispatch_compilers['FOO=bar rspec'] = 'rspec'
```

An ambitious contributor could probably fix this for good by changing this pattern to strip off all environment variable style prefixes:

https://github.com/tpope/vim-dispatch/blob/c88f1b1e4fd428d826fa38c272ed80b6518d37eb/autoload/dispatch.vim#L627

Shell syntax varies for this, so it might be best to stick to targeting the mostly portable `env FOO=bar rspec` variant.
