### ISSUE TITLE
Vim hangs and process doesn't complete

### ISSUE THREAD

**Issue by graywh** [tpope/vim-dispatch#318]
macOS 10.13.6 High Sierra
MacVim snapshot 172 (Vim 8.2.3455)
dispatch.vim a99a671aff
tmux 3.2a
iTerm 3.3.12
Rails 5.2.6
Rspec 3.7.1
Rspec-rails 3.7.2

When I open a spec file from the terminal and run `:Rake` on it, a new tmux window opens, but the spec command doesn't terminate and I never regain control of vim.

`shellpipe=2>&1| tee`

**Comment by graywh** [comment]
![image](https://user-images.githubusercontent.com/6110/141355368-b08bf73c-5ca4-4396-97ae-06fb5945cce4.png)

**Comment by tpope** [comment]
Is the `ruby` process still running? Anything else related to that tmux pane still running?

**Comment by graywh** [comment]
no ruby, just other stuff related to opening the pane

```
1:23PM   0:00.01 /bin/zsh -c (tmux new-window -n 'rake' -P -t ':' 'exec env -i SHELL=/bin/zsh HOME=/Users/graywh TMUX='\''/tmp//tmux-501/default,976,0'\'' TMUX_PANE='\''%68'\'' /bin/zsh /var/folders/tx/c1mn6ngn7w1496t0_j4xlg3m0000gn/T/vUnatHH/1.dispatch'|tee /var/folders/tx/c1mn6ngn7w1496t0_j4xlg3m0000gn/T/vUnatHH/2|xargs -I {} tmux pipe-pane -t {} '/usr/bin/sed -l -e "s/^M^M*$//" -e "s/.*^M//" -e "s/^[\[K//g"  -e "s/.*^[\[2K^[\[[01]G//g" -e "s/.*^[\[?25h^[\[0G//g" -e "s/^[\[[0-9;]*m//g" -e "s/^O//g" > /var/folders/tx/c1mn6ngn7w1496t0_j4xlg3m0000gn/T/vUnatHH/1')>/var/folders/tx/c1mn6ngn7w1496t0_j4xlg3m0000gn/T/vUnatHH/6 2>&1
1:23PM   0:00.00 tee /var/folders/tx/c1mn6ngn7w1496t0_j4xlg3m0000gn/T/vUnatHH/2
1:23PM   0:00.00 xargs -I {} tmux pipe-pane -t {} /usr/bin/sed -l -e "s/^M^M*$//" -e "s/.*^M//" -e "s/^[\[K//g"  -e "s/.*^[\[2K^[\[[01]G//g" -e "s/.*^[\[?25h^[\[0G//g" -e "s/^[\[[0-9;]*m//g" -e "s/^O//g" > /var/folders/tx/c1mn6ngn7w1496t0_j4xlg3m0000gn/T/vUnatHH/1
1:23PM   0:00.04 /bin/zsh /var/folders/tx/c1mn6ngn7w1496t0_j4xlg3m0000gn/T/vUnatHH/1.dispatch
1:23PM   0:00.00 sh -c /usr/bin/sed -l -e "s/^M^M*$//" -e "s/.*^M//" -e "s/^[\[K//g"  -e "s/.*^[\[2K^[\[[01]G//g" -e "s/.*^[\[?25h^[\[0G//g" -e "s/^[\[[0-9;]*m//g" -e "s/^O//g" > /var/folders/tx/c1mn6ngn7w1496t0_j4xlg3m0000gn/T/vUnatHH/1
1:23PM   0:00.01 /usr/bin/sed -l -e s/^M^M*$// -e s/.*^M// -e s/^[\[K//g -e s/.*^[\[2K^[\[[01]G//g -e s/.*^[\[?25h^[\[0G//g -e s/^[\[[0-9;]*m//g -e s/^O//g
1:23PM   0:00.03 /Applications/MacVim.app/Contents/MacOS/Vim --servername VIM7 --remote-expr DispatchComplete(1)
1:24PM   0:00.01 (sh)
1:24PM   0:00.00 (sh)
1:24PM   0:00.04 (ioreg)
1:24PM   0:00.01 (awk)
```

**Comment by tpope** [comment]
What if you do the `:set shellpipe=2>&1\|tee` trick to disable pipe-pane?

**Comment by graywh** [comment]
not sure why `2>&1\| tee` (original value noted above) has color, but setting it to `2>&1\|tee` gives no color, but same result

**Comment by tpope** [comment]
That's a deliberate feature (with a dubious interface).

Looking closer at the process list, I see `--servername VIM10` and the like in there, which tells me `:echo v:servername` is `VIM10`. Can you confirm? And can you think of any reason it might be set? When I try with terminal MacVim—calling `/Applications/MacVim.app/Contents/MacOS/bin/vim` directly—I get an empty string. This is the heart of the problem.

**Comment by graywh** [comment]
`v:servername` is set every time I open via `mvim`

If I use `/Applications/MacVim.app/Contents/bin/vim` directly, `v:servername` is blank, but I get a pane instead of a window and it doesn't close and return to vim

![image](https://user-images.githubusercontent.com/6110/141363834-0553f93f-bccf-4718-aa3c-35c2d3eb58a8.png)

Ctrl-c terminates some command

![image](https://user-images.githubusercontent.com/6110/141363890-2b3da7c7-deab-4059-bc18-b6d728947760.png)

**Comment by tpope** [comment]
I misread your screenshot as being a terminal instance of MacVim. That answers one question but raises several more. Let's start with two:

* If you call `/Applications/MacVim.app/Contents/MacOS/Vim --servername VIM10 --remote-expr 0`, does it hang? Use the appropriate `v:servername`, and call it from inside the same tmux session that you're experiencing the issue.
* You said "I never regain control of vim". I take it that means Vim is hanging too? If so, what happens if you CTRL-C?

**Comment by graywh** [comment]
1. 0 is echo'd to the terminal
2. Ctrl-c does nothing once MacVim hangs, can't even close the window, only Cmd-Q/quit

**Comment by tpope** [comment]
I tried with the same MacVim patch level and can't reproduce any of this. An unrecoverable hang makes me think this is _not_ a Dispatch problem, but I'm not sure what the problem _is_. Other things you can try.

* Start a long running command, and before it finishes, do `:call DispatchComplete(1)`. Make sure the `1` matches the number seen at the end of the command. (It will always be 1 on a fresh Vim instance.)
* Disable tmux make support with `:let g:dispatch_no_tmux_make = 1`, and see if the job adapter breaks the same way. Or try outside of a tmux session.

**Comment by graywh** [comment]
Well, it's been working fine for weeks now.
