### ISSUE TITLE
Terminal strategy with debugger capability

### ISSUE THREAD

**Issue by bekicot** [tpope/vim-dispatch#319]
I'm not sure if it is my configuration or this is not supported by dispatch yet.

https://user-images.githubusercontent.com/1826884/141691538-403190a6-8930-4d94-9ef8-07d6247598a2.mov

When I use tmux strategy, debugger works.

**Comment by teoljungberg** [comment]
Have you seen https://github.com/tpope/vim-dispatch/pull/250? It’s opt in via setting `g:dispatch_experimental=1`

**Comment by tpope** [comment]
It's opt-out, not opt-in. But yes, using `:.Spawn` rather than `:Dispatch` is the way to run the default dispatch in a terminal.

**Comment by teoljungberg** [comment]
Now I remember, thanks for clarifying!
