### ISSUE TITLE
Cannot close last window

### ISSUE THREAD

**Issue by kaihowl** [tpope/vim-dispatch#323]
When I have only the quickfix window open and run `:Make`, I get 
```
Error detected while processing function dispatch#compile_command:
line   91:
E444: Cannot close last window
```
caused by [this line](https://github.com/tpope/vim-dispatch/blob/3505862b3898be5db3c78ba1b92c703349478d68/autoload/dispatch.vim#L915). Is my workflow just weird or should this indiscriminate `cclose` be surrounded by a check if this is the only open window?

**Comment by kaihowl** [comment]
That was a quick fix. Thank you, @tpope!

**Comment by kaihowl** [comment]
I verified this locally now and found:
```
Error detected while processing function <lambda>11[1]..dispatch#complete[14]..<SNR>66_cwindow:
line   11:
E444: Cannot close last window
```
This seems to stem from [here](https://github.com/tpope/vim-dispatch/blob/09faff31c94e33be56eb792f6cc5f23ee582caf2/autoload/dispatch.vim#L1367).

**Comment by tpope** [comment]
Your turn.

**Comment by kaihowl** [comment]
> Your turn.

My pleasure.
