### ISSUE TITLE
ctrl-c of a ":Make" dispatched command immediately terminates command

### ISSUE THREAD

**Issue by KaiHoewelmeyer-TomTom** [tpope/vim-dispatch#326]
Reproduction scenario:

#### test.sh
```
#!/bin/sh
rm -rf output.log
cleanup() {
  echo "sleeping 2 seconds" >> output.log
  sleep 2
  echo "reach end of trap" >> output.log
}
trap "cleanup" INT
sleep 5
echo "Reached end of execution" >> output.log
```

Run `:Dispatch ./test.sh` from (n)vim within a tmux session. Within 5 seconds, switch to the new tmux pane, and press `<ctrl-c>`. Observe that the tmux pane is immediately quit. The log only contains the first echo'ed words of the `cleanup` function. The remainder is not there.

This used to work when `pipe-pane` was used for tmux. With [this commit](https://github.com/tpope/vim-dispatch/commit/3505862b3898be5db3c78ba1b92c703349478d68) changed the default behavior. Since the default behavior was changed intentionally to fix some other issues, I am cautious to just change the default back to the original behavior in my local configuration (which would of course fix my issue.)

Instead, I would like to understand if the use case of "interactively" stopping the command with `<ctrl-c>` already makes me subject to the _Do not use :Make/:Dispatch for interactive programs, use :Start instead_ advice. If so, this ticket can be closed and the problem is on my end.

Thank you for your time looking into this!

**Comment by KaiHoewelmeyer-TomTom** [comment]
Unfortunately, there is no clear behavior:

- _Screen_ behaves the same way as tmux: The process ends prematurely.
- _Job_ behaves as expected: The cleanup is allowed to proceed.

Other adapters I did not test.

The testing for _Job_ might have been flawed. Since I failed to figure out how to properly stop the job from within nvim (and the job always runs background), I resorted to desperate measures and send `kill -2 -<ppid>` for the respective process group that was started. 

If you have more things I should test, I am happy to assist you.

**Comment by tpope** [comment]
I guess the flagship adapter not supporting CTRL-C seals the deal on this one. CTRL-C is not an official interface, and I won't be digging in further. I think your desired behavior is reasonable, and if you wanted to implement it, I would take a look at the PR. It would be nice if CTRL-C was consistent across all adapters that do support it.

The official way to kill a dispatch is `:AbortDispatch`, and I would be willing to entertain further discussion about how _that_ should behave.
