### ISSUE TITLE
Running :Make resets `scrolloff` to 0

### ISSUE THREAD

**Issue by brokenbyte** [tpope/vim-dispatch#330]
I have my scrolloff set to 999 to keep my cursor in the middle of my screen, 
but after running `:Make` it gets reset to 0.

Is there a way to make it persist?

running neovim 0.6.1

**Comment by tpope** [comment]
I keep mine at 1 and have never seen it reset. Can you check `:verbose set scrolloff?` after it happens and see if there's a culprit?

**Comment by cristobaltapia** [comment]
Hi @tpope,

I have this problem too. This is what I get with `:verbose set scrolloff?`:

```
 scrolloff=0                                                                                                                                                                               
        Last set from Lua line 10
```
Is there a way to get more info about this?

Seems it has something to do with Lua, so I guess it is not really something with vim-dispatch... but it happens after using the `:Make` command only. Maybe you have a hint for this?
