### ISSUE TITLE
Is one of the mappings supposed to run the last thing you dispatched?

### ISSUE THREAD

**Issue by shmup** [tpope/vim-dispatch#335]
Just a question, I can't figure out if I, for example: `:Dispatch! foo`, should be able to easily run that again, as simple as \``<CR>`

My memory is fuzzy, but I thought I used to know the incantation to re-run the last thing I dispatched.. and may figure it out mere minutes after opening this ticket, as it generally goes...

(can't for the life of me figure out how to get Github to render that w/ a leading backtick next to `<CR>` heh)

**Comment by shmup** [comment]
Ha, ok so it's `! which doesn't actually it, just populates the prompt.

Also that is a bit of finger gymnastics. No sweat, though, I will provide my own mapping as one does.

(Open to you telling me I should be doing this differently)

**Comment by shmup** [comment]
Do you see any problems with `nnoremap mm :Dispatch!<CR>`

**Comment by shmup** [comment]
1) I am upset I forgot that I'd be wiping out a mark.. smh

2) I did try  `<CR> however, even if you run a manual `:Dispatch`, `<CR> always respects the `makeprg` (in my tests)

**Comment by tpope** [comment]
> 2. I did try that   however, even if you run a manual `:Dispatch`, that mapping you suggested always respects the `makeprg`, instead of re-running my initial manual `:Dispatch ...` (in my tests)

Whoops, I was thinking of rails.vim. I guess you could roll your own with something like `:exe 'Dispatch' dispatch#request().command`.
 
> (can you explain how you properly write that mapping surrounded by backticks, I'm trying nested ticks but it never works heh)

`<code>`

**Comment by shmup** [comment]
Appreciate it. Though, `<code>` wasn't the full solution in my test.

I had to do this dumb shit:

```
<code>`\<CR\></code>
```

Ala.. <code>`\<CR\></code>

**Comment by tpope** [comment]
> Whoops, I was thinking of rails.vim.

This was wrong; I had it right the first time. [The default task is explicitly set in the quickfix window](https://github.com/tpope/vim-dispatch/blob/a58eaaa41f895fb729a36740a91608ed47706636/autoload/dispatch.vim#L1378-L1382). Check the output of `:FocusDispatch` to see if something else is overriding it.

**Comment by shmup** [comment]
Oops, "get told"

yeah I'll investigate that. ty sir :vulcan_salute:
