### ISSUE TITLE
[Feature Request] customize exit_cb on terminal strategy

### ISSUE THREAD

**Issue by jiz4oh** [tpope/vim-dispatch#337]
Hi @tpope, Is it possible to have customize exit_cb function? So I can do something myself after I close the terminal window

**Comment by tpope** [comment]
#135

**Comment by jiz4oh** [comment]
hey bro, sorry for my bad English, let me clarify more clear.

after I call Start or Spawn command, these two function will be called,

[dispatch#start_command](https://github.com/tpope/vim-dispatch/blob/00e77d90452e3c710014b26dc61ea919bc895e92/autoload/dispatch.vim#L537)
[dispatch#spawn_command](https://github.com/tpope/vim-dispatch/blob/00e77d90452e3c710014b26dc61ea919bc895e92/autoload/dispatch.vim#L482)

under terminal strategy, [an exit callback](https://github.com/tpope/vim-dispatch/blob/00e77d90452e3c710014b26dc61ea919bc895e92/autoload/dispatch/terminal.vim#L59) is added to terminal. I have something need todo after terminal exited and I read the code but I don't find anyway to customize my own exit callback.

Is it possible to fire a customize event or anything you feel well after terminal exited?

**Comment by tpope** [comment]
That exit callback is an implementation detail. There is no API to hook into it. Your options are:

1. Use one of Dispatch.vim's custom autocommands, like that `QuickFixCmdPost cgetfile`.
2. Use a built-in autocommand, like `TermClose` from Neovim or `BufDelete` from regular Vim.

**Comment by jiz4oh** [comment]
Do you mind me to open a pr for add a User event there so can do something from user side after terminal exited only in the terminal buffer which created by vim-dispatch instead of `TermClose` of `BufDelete` that affects all buffers?

**Comment by tpope** [comment]
I'm open to adding other autocommands, but they should be generic to all adapters, not something that's specific to the terminal adapter.

> ...  instead of `TermClose` of `BufDelete` that affects all buffers?

They do operate on all buffers, but you could still achieve your goals if you recorded the terminal buffer immediately after starting the task, and checked for it in `TermClose` or `BufDelete`.

**Comment by jiz4oh** [comment]
Emmm, sorry, I know few things about other adapters except Terminal adapter. Any suggestions for record the terminal buffer which start from vim-dispatch? I Know the `TermOpen` or `TerminalWinOpen` autocommands, but I cannot distinguish the vim-dispatch terminal buffer or other terminal buffers.

**Comment by tpope** [comment]
Immediately _after_ you call `:Start`, you should be able to grab the buffer number of the current buffer. Then check for that buffer number in `TermClose` or whatever.

**Comment by jiz4oh** [comment]
nice, thank you for your patient!!
