### ISSUE TITLE
Jump to errors produced by sanitizers and CTest

### ISSUE THREAD

**Issue by rafaelrojasmiliani** [tpope/vim-dispatch#341]
I'm using dispatch with cmake4vim and running a test (using gtest) what is runned with the CTest command of cmake4vim. My project workspace is `/workspace` and is the same folder where I open vim.

- CTest (with gtest) generates error lines like:
```
6: /workspace/tests/manifold_test.cpp|31| Failure
```
Dispatch will try to open a file in the folder `/workspace/6: /workspace/tests`
- ASAN produces error like
```
||     #3 0x559d46228838 in manifolds::MatrixManifold<20l, 30l>::MatrixManifold(manifolds::MatrixManifold<20l, 30l> const&) /workspace/include/Manifolds/LinearManifolds/LinearManifolds.hpp:97
```
Dispatch is not capable of open it.

In principle this look simple to implement. But I don't have idea of where to search. Can someone give me a hand to understand where to start?

**Comment by tpope** [comment]
The documentation you seek is at `:help write-compiler-plugin`.
