### ISSUE TITLE
How to properly filter output with errorformat

### ISSUE THREAD

**Issue by MarcelRobitaille** [tpope/vim-dispatch#342]
I have everything set up so that if I call `:make` and then `:copen`, I only see errors in my quickfix list.

```lua
vim.opt.makeprg = '~/path/to/custom/script.sh'
vim.opt.errorformat = '%f:%l:%c:\\ %tnfo\\ %n:\\ %m,%-G%.%#'
```

The second formatter handles this, taken from [here](https://vi.stackexchange.com/questions/18846/ignore-lines-in-errorformat).

I want to use Dispatch to run jobs in the background. I thought it would "just work", but if I `:Make` (or `:Make!`) and then `:Copen`, I see all lines output by my script, not only the errors. If I `verbose set errorformat`, I see:
```
errorformat=%f:%l:%c:\ %tnfo\ %n:\ %m,
        Last set from ~/.local/share/nvim/site/pack/packer/start/vim-dispatch/autoload/dispatch.vim line 1387
```

I read through `:help dispatch`, and thought maybe I needed to configure a compiler with its own errorformat, and that dispatch would set errorformat to what I have configured for that compiler. I read `:help :CompilerSet`, and created `~/.config/nvim/after/compiler/custom.vim` with the contents:
```vim
CompilerSet makeprg=~/path/to/custom/script.sh errorformat=%f:%l:%c:\ %tnfo\ %n:\ %m,%-G%.%#
```

I also tried in two lines like in `:help :CompilerSet`:
```vim
CompilerSet makeprg=~/path/to/custom/script.sh
CompilerSet errorformat=%f:%l:%c:\ %tnfo\ %n:\ %m,%-G%.%#
```

However, if I `:compiler custom`, `:Make`, and `:Copen`, same thing. My `errorformat` is incorrectly set on line 1387 again.

How do I configure Dispatch's `errorformat`? I read through `:help dispatch` and the readme, but I only see one reference to `errorformat` and it doesn't really tell me how to configure it. I don't see *anything* about Dispatch mutating `errorformat` on me.

```
:Dispatch[!] [options] {program} [arguments]
                        Find a compiler plugin that sets 'makeprg' to
                        {program} and use its 'errorformat' to dispatch a
                        |:Make| for the given {program} and [arguments].  If
                        no compiler plugin is found, the generic format
                        %+I%.%# is used.
```

I tried to read the Dispatch source code, but I don't know vimscript well at all.

I am using `NVIM v0.10.0-dev-737+gdf2f5e391` and Debian 11

**Comment by MarcelRobitaille** [comment]
To be clear, it still correctly matches the actual errors, it just also shows non-matches. If anyone knows a better way to show non-matches, I would also accept that solution.

**Comment by tpope** [comment]
A lot of compiler plugins uses `%-G%.%#` to aggressively hide all unparsed output, even helpful output, by default. With the built-in `:make`, this isn't a big deal, because the full output shows up before a "press enter" prompt. But with `:Make`, all that output is lost forever. Thus by default Dispatch will strip `%-G%.%#` off of `'errorformat'`.

I don't recommend it, but if you want, you can add a second `%-G%.%#` to `'errorformat'` to force Dispatch to respect it.
