### ISSUE TITLE
Add variable with :Dispatch returncode similar to `v:shell_error`

### ISSUE THREAD

**Issue by leonschreuder** [tpope/vim-dispatch#347]
I intended to build a vim-airline extension for my status bar, that can show me if the last command I ran has succeeded or failed. I assumed the `v:shell_error` would hold the output for :Dispatch commands, but this is not the case. It doesn't appear that there is another way to determine the last exitcode. And it seems as though we can't even set `v:shell_error` from vimscript, so my questions are these:

- Is it possible to set the v:shell_error in some magical way, oh god of vimscript?
- If not, would you be willing to accept a PR that adds a new (global?) variable, that holds the last result of :Dispatch?

**Comment by tpope** [comment]
> I intended to build a vim-airline extension for my status bar, that can show me if the last command I ran has succeeded or failed. I assumed the `v:shell_error` would hold the output for :Dispatch commands, but this is not the case. It doesn't appear that there is another way to determine the last exitcode. And it seems as though we can't even set `v:shell_error` from vimscript, so my questions are these:
> 
> * Is it possible to set the v:shell_error in some magical way, oh god of vimscript?

It's gross, but you could do something like `system('exit 17')`.

> * If not, would you be willing to accept a PR that adds a new (global?) variable, that holds the last result of :Dispatch?

It's available at `dispatch#request().status`. Note that if a job is actively running, it won't be set.
