### ISSUE TITLE
Support passing range to a command's stdin

### ISSUE THREAD

**Issue by hseg** [tpope/vim-dispatch#355]
I have a slow filter I want to run on one of my buffers (i.e. `:%!yt fmt batch`), and I'd like the others to be available while it runs. Currently, it doesn't seem possible to do this with dispatch -- it seems more focused on either running a compiler/analytic on the current file or running an arbitrary unrelated process.
Design alternatives:
- Once the process has finished, put the stdout in the given range, regardless of its current contents
- Lock the buffer for modification while the filter is running
- Always output to a scratch buffer, with the expectation the user should copy the contents back. This suggests an obvious interface -- allow `:Start/:Spawn` to take a range which is used as stdin.

**Comment by tpope** [comment]
Do you want to _see_ the output as it's being generated, for example in a tmux pane? If not, I don't think Dispatch brings much to the table here. Would be easier to just wrap `jobstart()`/`job_start()` directly.

**Comment by hseg** [comment]
Indeed, and searching more I found that <https://www.reddit.com/r/neovim/comments/1377lwn> should (I'm afk, can't test) do precisely this. Inconvenient that it isn't packaged up, but that is easily fixable.
Thanks!

**Comment by hseg** [comment]
In fact, it turns out that `:term` is already close enough to what I want that I can adapt around the difference. Thanks!
