### ISSUE TITLE
no color when running rspec with dispatch

### ISSUE THREAD

**Issue by dfang** [tpope/vim-dispatch#51]
https://github.com/thoughtbot/vim-rspec/issues/27

thanks !

**Comment by dimanyc** [comment]
any idea why the color would flicker like so:
![rspec_bug](https://user-images.githubusercontent.com/6678600/38781377-9cc4c87c-40b1-11e8-99a5-ab99b5f91dc4.gif)

**Comment by tpope** [comment]
That's entirely contained within the 3rd party Neovim adapter.
