### ISSUE TITLE
Dispatch setup with `py.test-wrapper` for py.test via compiler/pytest.vim

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-dispatch#71]
I am trying to setup dispatch with `py.test`, and to complicate things I have a `py.test-wrapper` script (which would wrap it in a call to envdir).

It gets called like this:

    dispatch#compile_command(0, "py.test-wrapper %", 0)

In function dispatch#compile_command..dispatch#compiler_for_program, line 10: let program = fnamemodify(matchstr(args, '\S\+'), ':t:r'):

    program: py

And `request.compiler` gets set to `pytest` (which is a different program, but the name of the plugin (pytest-vim-compiler/compiler/pytest.vim), where I have changed the `CompilerSet` line (adding `-wrapper`):

    CompilerSet makeprg=py.test-wrapper\ --tb=short\ -q
 
FWIW, when I wrap the call to `vim` with `envdir` directly, and not use the `-wrapper` script, it appears to work as expected, using `Dispatch py.test %`.

While it works for me currently, I still wanted to provide this as feedback.

From a quick glance it looks like the problem might be that the `-wrapper` at the end causes a non-match somewhere, and maybe the plugin name `pytest` ends up being used as the command to be run (again: pytest is different from py.test).

btw: `dispatch#compile_command..dispatch#compiler_for_program` could maybe cache its result(s)?
(I have stopped debugging there (via `:debug Dispatch ...`), because I have found no easy way to skip the tedious for loops (I have a lot of plugins)).

I am using current master (49307b7).

**Comment by blueyed** [comment]
The `ComilerSet` via [pytest-vim-compiler/compiler/pytest.vim](https://github.com/5long/pytest-vim-compiler/blob/master/compiler/pytest.vim) is:

    CompilerSet makeprg=py.test\ --tb=short\ -q

1. This does not get matched by the `full` check, because the backslashes are not being taken into account with the comparison (`if !empty(full) && strpart(args.' ', 0, len(full)+1) ==# full.' '`).

2. Then there need to be additional modifications, like the `:r` you've mentioned (provided in https://github.com/tpope/vim-dispatch/pull/121).

**Comment by tpope** [comment]
I would expect `full` to work because the backslashes are stripped out with `substitute(..., '\\\(.\)', '\1', 'g')`.

**Comment by tpope** [comment]
That said, I am willing to try your change.
