### ISSUE TITLE
Update quickfix window automatically

### ISSUE THREAD

**Issue by Morantron** [tpope/vim-dispatch#75]
Hi! I'm wondering if it's possible to automatically update the quickfix window on builds using `:Make!` as errors appear on the tmux pane.

In my case, runtime errors are read from a local server ( makeprg is just a curl to that server ), and it'd be awesome if they were automatically reflected on quickfix without having to `:Copen` ( lazy I know :B ).

Just wanted to know if it physically possible to do this or if you just should hit `:Copen` to refresh the quickfix window and stop whining.

Thanks! :fist:

**Comment by guilpejon** [comment]
Thank you @waiting-for-dev, I was looking for that!
