### ISSUE TITLE
Option to rerun last command

### ISSUE THREAD

**Issue by waiting-for-dev** [tpope/vim-dispatch#80]
As discussed in tpope/vim-rails#316, it would be nice to have and option to rerun last command, something like [benmills/vimux](https://github.com/benmills/vimux) do (in this case, only for tmux).

**Comment by filipegiusti** [comment]
I have the same problem as @waiting-for-dev, I have a mapping to run the test under the cursor `:execute "Dispatch rake test % TESTOPTS='--line" line(".") "'"<CR>` and I would like to go to the implementation file and keep repeating the last command run. It's impractical to use `:Focus` and impossible to use projections or localvimrc.

I would say a solution would be to start only rerunning explicit dispatches with `:DispatchLast` and improve from there. I also liked the solution of `:DispatchLast Runner`.

Thoughts @tpope? Would you accept a PR with that?

**Comment by tpope** [comment]
I've pushed up my stagnant attempt to the `repeat-last` branch. Use `:Dispatch -` to invoke. I still haven't found a satisfactory solution to which previous invocations we include.

I don't like `:DispatchLast` because that means you can't shorten `:Dispatch` to `:Disp` or whatever. Also, `:DispatchLast Runner` assume knowledge of the implementation of `:Runner` which we don't have.

**Comment by justinmk** [comment]
I like the `-` convention, good call.

**Comment by waiting-for-dev** [comment]
Hey, sorry for coming back so late... :) Just tried `repeat-last` branch and it seems it's working well. Any plan about merging it to master?

**Comment by tpope** [comment]
I don't remember why I didn't bring this up years ago, but `:Copen` sets the quickfix window's dispatch default to whatever command's output you're looking at. So effectively, `:Copen|Dispatch` repeats the last task. Is that good enough? The `-` implementation is pretty simple, but all things being equal I'd rather not commit to more code.

**Comment by waiting-for-dev** [comment]
I think is ok. Now I'm using `vim-test` to run tests so I'm using what it provides to run last test (which anyway goes through `vim-dispatch` as strategy in use). Anyway, I think that as it is a common scenario it deserves to be aliased out of the box or, at least, to be documented in the README.

**Comment by tpope** [comment]
Well, that's the official answer for now. The quickfix enhancements like `:chistory` in Vim 8 have given me some ideas for a much more robust rerun mechanism, so stay tuned.

**Comment by yunake** [comment]
i am staying tuned for sure :)
in the meantime, maybe you could share your idea so that we could try to sketch out an implementation?
