### ISSUE TITLE
RVM + tmux: Using wrong Ruby version

### ISSUE THREAD

**Issue by jclem** [tpope/vim-dispatch#9]
When I run `:Dispatch rspec` in MacVim or vim outside of tmux, there are no problems. However, when running the same command in tmux inside of vim, the command fails, and the backtrace shows whichever version of Ruby I first started any other tmux session in (i.e. not the correct one if I have any previously opened sessions), but still displays syntax errors on Ruby 1.9-style hashes, as if it's really using Ruby 1.8.

**Comment by goyalmunish** [comment]
I had the same issues. But adding following at the top of `~/.tmux.conf` worked:

```
set-option -g default-shell /bin/zsh
```
My environment is:
OS: Mac 10.12.4
tmux 2.4
zsh 5.4.2 (x86_64-apple-darwin16.7.0)
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
rvm 1.29.3 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
