### ISSUE TITLE
(only) tmux doesn't keep pane open in neovim when process exits with non-0 code

### ISSUE THREAD

**Issue by geoffharcourt** [tpope/vim-dispatch#92]
I realize supporting neovim is not a project requirement, but since vim-dispatch seems to handle every other case I've thrown at it, I'm hoping to figure out if there's a straightforward fix. Here's what I'm doing:
1. Run rspec in non-tmux neovim session with an intentionally failing test: dispatch keeps test pane open
2. Run teaspoon in non-tmux neoviim session with an intentionally failing test: dispatch keeps test pane open
3. Run rspec or teaspoon in neovim session within tmux with a failing test: dispatch closes the (tmux) pane, which makes it seem like the process exited with status 0, but the failure is visible if you run `:Copen`.

Teaspoon, for example, exits with a code of 1, the vim/neovim difference doesn't matter outside of tmux.

I have been attempting to read the [tmux.vim](https://github.com/tpope/vim-dispatch/blob/master/autoload/dispatch/tmux.vim) to figure out why this might behave differently in neovim vs. vim but only in tmux with no success.

**Comment by Vincent-Carrier** [comment]
Still experiencing this issue on Neovim 0.4

**Comment by tpope** [comment]
Is the output *identical* in `:Copen` with and without tmux?

**Comment by Vincent-Carrier** [comment]
Couldn’t confirm, I’m running Linux without any GUI right now. But I figured it might be because I have this inside my .tmux.conf
```
set -g base-index 1
 set -g pane-base-index 1
```

Does dispatch do anything like `kill-pane -a -t 0` ? Cause that would surely interfere.
