### ISSUE TITLE
Feature: Allow to define the type and size of the split

### ISSUE THREAD

**Issue by RobertBuhren** [tpope/vim-dispatch#98]
It would be nice to define the size and the type of the split for a given command. 

E.g. I use "Make" to compile my program and i would like to use "Start" to start a virtual machine which executes my program in a vertical split. So something like "VertStart "program".

Regards,

Robert

**Comment by tpope** [comment]
Yeah, see tbone. `:VertStart` would only make sense for the tmux adapter so you won't find it here.

Another approach, which I favor, is to `:Start` normally, then use a tmux keybinding to rearrange afterwords.  For example:

    bind H join-pane -h -t !

This gives a lot more flexibility then a bunch of single purpose Vim commands.
